version = '3.5.0'

[cache]
dir = '$KAMEHOUSE_DATA_DIR/cache'
transcodedir = '$KAMEHOUSE_DATA_DIR/cache/transcode'

[database]
name = 'kamehouse'

[extensions]
dir = '$KAMEHOUSE_DATA_DIR/extensions'

[logs]
dir = '$KAMEHOUSE_DATA_DIR/logs'

[manga]
downloaddir = '$KAMEHOUSE_DATA_DIR/manga'
localdir = '$KAMEHOUSE_DATA_DIR/manga-local'

[offline]
assetdir = '$KAMEHOUSE_DATA_DIR/offline/assets'
dir = '$KAMEHOUSE_DATA_DIR/offline'

[server]
host = '127.0.0.1'
offline = false
port = 43211
usebinarypath = true

[web]
assetdir = '$KAMEHOUSE_DATA_DIR/assets'
