/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as CollectionsIdRouteImport } from './routes/collections/$id'
import { Route as SeriesSeriesIdIndexRouteImport } from './routes/series/$seriesId/index'

const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdIndexRoute = SeriesSeriesIdIndexRouteImport.update({
  id: '/series/$seriesId/',
  path: '/series/$seriesId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/collections/$id': typeof CollectionsIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/home/': typeof HomeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/series/$seriesId/': typeof SeriesSeriesIdIndexRoute
}
export interface FileRoutesByTo {
  '/collections/$id': typeof CollectionsIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/home': typeof HomeIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/series': typeof SeriesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/series/$seriesId': typeof SeriesSeriesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/collections/$id': typeof CollectionsIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/home/': typeof HomeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/series/$seriesId/': typeof SeriesSeriesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/collections/$id'
    | '/movies/$movieId'
    | '/admin/'
    | '/collections/'
    | '/home/'
    | '/movies/'
    | '/series/'
    | '/settings/'
    | '/series/$seriesId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/collections/$id'
    | '/movies/$movieId'
    | '/admin'
    | '/collections'
    | '/home'
    | '/movies'
    | '/series'
    | '/settings'
    | '/series/$seriesId'
  id:
    | '__root__'
    | '/collections/$id'
    | '/movies/$movieId'
    | '/admin/'
    | '/collections/'
    | '/home/'
    | '/movies/'
    | '/series/'
    | '/settings/'
    | '/series/$seriesId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SeriesSeriesIdIndexRoute: typeof SeriesSeriesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId/': {
      id: '/series/$seriesId/'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId/'
      preLoaderRoute: typeof SeriesSeriesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SeriesSeriesIdIndexRoute: SeriesSeriesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
