import { GettingStarted_Variables } from "@/api/generated/endpoint.types"
import type { Models_Settings } from "@/api/generated/types"
import { z } from "zod"



export const _gettingStartedSchema = z.object({
    enableTranscode: z.boolean().optional().default(false),
    debridProvider: z.string().optional().default("none"),
    debridApiKey: z.string().optional().default(""),
})

export const settingsSchema = z.object({
    library: z.object({
        libraryPath: z.string().optional().default(""),
        autoScan: z.boolean().optional().default(false),
        tmdbApiKey: z.string().optional().default(""),
        tmdbLanguage: z.string().optional().default("es-MX"),
        hideAudienceScore: z.boolean().optional().default(false),
        enableRichPresence: z.boolean().optional().default(false),
        enableAnimeRichPresence: z.boolean().optional().default(false),
        openWebURLOnStart: z.boolean().optional().default(false),
        refreshLibraryOnStart: z.boolean().optional().default(false),
        richPresenceHideKameHouseRepositoryButton: z.boolean().optional().default(false),
        richPresenceShowPlatformMediaButton: z.boolean().optional().default(false),
        richPresenceShowPlatformProfileButton: z.boolean().optional().default(false),
        richPresenceUseMediaTitleStatus: z.boolean().optional().default(true),
        autoPlayNextEpisode: z.boolean().optional().default(true),
        autoDetectSkipTimes: z.boolean().optional().default(true),
        enableWatchContinuity: z.boolean().optional().default(false),
        seriesPaths: z.array(z.string()).optional().default([]),
        moviePaths: z.array(z.string()).optional().default([]),
        scannerMatchingThreshold: z.number().optional().default(0.5),
        scannerMatchingAlgorithm: z.string().optional().default(""),
        useFallbackMetadataProvider: z.boolean().optional().default(false),
        vcTranslate: z.boolean().optional().default(false),
        vcTranslateApiKey: z.string().optional().default(""),
        vcTranslateProvider: z.string().optional().default(""),
        vcTranslateTargetLanguage: z.string().optional().default(""),
        scannerUseLegacyMatching: z.boolean().optional().default(false),
        scannerConfig: z.string().optional().default(""),
        scannerStrictStructure: z.boolean().optional().default(false),
        scannerProvider: z.string().optional().default("tmdb"),
        disableLocalScanning: z.boolean().optional().default(false),
        primaryMetadataProvider: z.string().optional().default("tmdb"),
        fanartApiKey: z.string().optional().default(""),
        omdbApiKey: z.string().optional().default(""),
    }),
    mediaPlayer: z.object({}),
    mediastream: z.object({
        transcodeEnabled: z.boolean().default(false),
        transcodeHwAccel: z.string().default("auto"),
        transcodePreset: z.string().default("fast"),
        disableAutoSwitchToDirectPlay: z.boolean().default(false),
        directPlayOnly: z.boolean().default(false),
        transcodeFfmpegPath: z.string().default(""),
        transcodeFfprobePath: z.string().default(""),
        transcodeHwAccelCustomSettings: z.string().default(""),
    }),
    theme: z.object({
        themeAnimeEntryScreenLayout: z.string().min(0).optional(),
        themeSmallerEpisodeCarouselSize: z.boolean().default(false),
        themeExpandSidebarOnHover: z.boolean().default(false),
        themeEnableColorSettings: z.boolean().default(false),
        themeBackgroundColor: z.string().min(0).default("#070707"),
        themeAccentColor: z.string().min(0).default("#6152df"),
        themeSidebarBackgroundColor: z.string().min(0).optional(),
        themeHideTopNavbar: z.boolean().default(false),
        themeEnableMediaCardBlurredBackground: z.boolean().default(false),
        themeLibraryScreenBannerType: z.string().default("dynamic"),
        themeLibraryScreenCustomBannerImage: z.string().default(""),
        themeLibraryScreenCustomBannerPosition: z.string().default("50% 50%"),
        themeLibraryScreenCustomBannerOpacity: z.number().default(10),
        themeLibraryScreenCustomBackgroundImage: z.string().default(""),
        themeLibraryScreenCustomBackgroundOpacity: z.number().default(10),
        themeLibraryScreenCustomBackgroundBlur: z.string().default("none"),
        themeEnableMediaPageBlurredBackground: z.boolean().default(false),
        themeDisableSidebarTransparency: z.boolean().default(false),
        themeDisableLibraryScreenGenreSelector: z.boolean().default(false),
        themeUseLegacyEpisodeCard: z.boolean().default(false),
        themeDisableCarouselAutoScroll: z.boolean().default(false),
        themeMediaPageBannerType: z.string().default("default"),
        themeMediaPageBannerSize: z.string().default("default"),
        themeMediaPageBannerInfoBoxSize: z.string().default("default"),
        themeShowEpisodeCardAnimeInfo: z.boolean().default(true),
        themeAnimeLibraryCollectionDefaultSorting: z.string().default("TITLE_ASC"),

        themeShowAnimeUnwatchedCount: z.boolean().default(true),

        themeHideEpisodeCardDescription: z.boolean().default(false),
        themeHideDownloadedEpisodeCardFilename: z.boolean().default(false),
        themeCustomCSS: z.string().default(""),
        themeMobileCustomCSS: z.string().default(""),
        themeUnpinnedMenuItems: z.array(z.string()).default([]),
        themeEnableBlurringEffects: z.boolean().default(false),
    }),
    notifications: z.object({
        disableNotifications: z.boolean().default(false),
        disableAutoScannerNotifications: z.boolean().default(false),
    }),
})

export const gettingStartedSchema = _gettingStartedSchema.extend({
    library: settingsSchema.shape.library,
    mediaPlayer: settingsSchema.shape.mediaPlayer,
    notifications: settingsSchema.shape.notifications.optional(),
})

export const getDefaultSettings = (data: z.infer<typeof gettingStartedSchema>, existingSettings?: Models_Settings | null): GettingStarted_Variables => ({
    library: {
        autoScan: data.library.autoScan ?? existingSettings?.library?.autoScan ?? false,
        openWebURLOnStart: existingSettings?.library?.openWebURLOnStart ?? false,
        refreshLibraryOnStart: existingSettings?.library?.refreshLibraryOnStart ?? false,
        autoPlayNextEpisode: data.library.autoPlayNextEpisode ?? existingSettings?.library?.autoPlayNextEpisode ?? true,
        autoDetectSkipTimes: data.library.autoDetectSkipTimes ?? existingSettings?.library?.autoDetectSkipTimes ?? true,
        enableWatchContinuity: data.library.enableWatchContinuity ?? existingSettings?.library?.enableWatchContinuity ?? true,
        seriesPaths: data.library.seriesPaths ?? existingSettings?.library?.seriesPaths ?? [],
        moviePaths: data.library.moviePaths ?? existingSettings?.library?.moviePaths ?? [],
        scannerMatchingThreshold: existingSettings?.library?.scannerMatchingThreshold ?? 0,
        scannerMatchingAlgorithm: existingSettings?.library?.scannerMatchingAlgorithm ?? "",
        useFallbackMetadataProvider: existingSettings?.library?.useFallbackMetadataProvider ?? false,
        scannerUseLegacyMatching: existingSettings?.library?.scannerUseLegacyMatching ?? false,
        scannerStrictStructure: existingSettings?.library?.scannerStrictStructure ?? false,
        scannerProvider: data.library.scannerProvider || existingSettings?.library?.scannerProvider || "tmdb",
        scannerConfig: existingSettings?.library?.scannerConfig ?? "",
        disableLocalScanning: data.library.disableLocalScanning ?? existingSettings?.library?.disableLocalScanning ?? false,
        tmdbApiKey: data.library.tmdbApiKey || existingSettings?.library?.tmdbApiKey || "",
        tmdbLanguage: existingSettings?.library?.tmdbLanguage || "es-MX",
        primaryMetadataProvider: data.library.primaryMetadataProvider || existingSettings?.library?.primaryMetadataProvider || "tmdb",
        fanartApiKey: data.library.fanartApiKey || existingSettings?.library?.fanartApiKey || "",
        omdbApiKey: data.library.omdbApiKey || existingSettings?.library?.omdbApiKey || "",
    },
    mediaPlayer: existingSettings?.mediaPlayer || {},
    enableTranscode: data.enableTranscode ?? existingSettings?.mediastream?.transcodeEnabled ?? false,
})


