package codegen

import (
	"cmp"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

const (
	typescriptFileName = "types.ts"
)

// Structs that are not directly referenced by the API routes but are needed for the Typescript file.
var additionalStructNames = []string{

	"debrid_client.StreamState",
	"extension_repo.TrayPluginExtensionItem",
	"vendor_habari.Metadata",
	"nativeplayer.PlaybackInfo",
	"nativeplayer.ServerEvent",
	"nativeplayer.ClientEvent",
	"mkvparser.SubtitleEvent",
	"nakama.NakamaStatus",
	"core.FeatureKey",
	"videocore.ClientEventType",
	"videocore.ServerEvent",
	"videocore.PlaybackState",
	"plugin_ui.WebviewSlot",
	"plugin_ui.WebviewOptions",
	"videocore.InSightData",
}

// GenerateTypescriptFile generates a Typescript file containing the types for the API routes parameters and responses based on the Docs struct.
func GenerateTypescriptFile(docsFilePath string, publicStructsFilePath string, outDir string, goStructStrs []string) {

	handlers := LoadHandlers(docsFilePath)

	goStructs := LoadPublicStructs(publicStructsFilePath)

	// e.g. map["models.User"]*GoStruct
	goStructsMap := make(map[string]*GoStruct)

	for _, goStruct := range goStructs {
		goStructsMap[goStruct.Package+"."+goStruct.Name] = goStruct
	}

	// Expand the structs with embedded structs
	for _, goStruct := range goStructs {
		for _, embeddedStructType := range goStruct.EmbeddedStructTypes {
			if embeddedStructType != "" {
				if usedStruct, ok := goStructsMap[embeddedStructType]; ok {
					goStruct.Fields = append(goStruct.Fields, usedStruct.Fields...)
				}
			}
		}
	}

	// Create the typescript file
	_ = os.MkdirAll(outDir, os.ModePerm)
	file, err := os.Create(filepath.Join(outDir, typescriptFileName))
	if err != nil {
		panic(err)
	}
	defer file.Close()

	// Write the typescript file
	file.WriteString("// This code was generated by codegen/main.go. DO NOT EDIT.\n\n")

	// Get all the returned structs from the routes
	// e.g. @returns models.User
	structStrMap := make(map[string]int)
	for _, str := range goStructStrs {
		structStrMap[str]++
	}
	for _, handler := range handlers {
		if handler.Api != nil {
			switch handler.Api.ReturnTypescriptType {
			case "null", "string", "number", "boolean":
				continue
			}

			structStrMap[handler.Api.ReturnGoType]++
		}
	}

	// Isolate the structs that are returned more than once
	sharedStructStrs := make([]string, 0)
	otherStructStrs := make([]string, 0)

	for k, v := range structStrMap {
		if v > 1 {
			sharedStructStrs = append(sharedStructStrs, k)
		} else {
			otherStructStrs = append(otherStructStrs, k)
		}
	}

	// Now that we have the returned structs, store them in slices
	sharedStructs := make([]*GoStruct, 0)
	otherStructs := make([]*GoStruct, 0)

	for _, structStr := range sharedStructStrs {
		// e.g. "models.User"
		structStrParts := strings.Split(structStr, ".")
		if len(structStrParts) != 2 {
			continue
		}

		// Find the struct
		goStruct, ok := goStructsMap[structStr]
		if ok {
			sharedStructs = append(sharedStructs, goStruct)
		}

	}
	for _, structStr := range otherStructStrs {
		// e.g. "models.User"
		structStrParts := strings.Split(structStr, ".")
		if len(structStrParts) != 2 {
			continue
		}

		// Find the struct
		goStruct, ok := goStructsMap[structStr]
		if ok {
			otherStructs = append(otherStructs, goStruct)
		}
	}

	// Add additional structs to otherStructs
	for _, structName := range additionalStructNames {
		if goStruct, ok := goStructsMap[structName]; ok {
			otherStructs = append(otherStructs, goStruct)
		}
	}

	//-------------------------

	referencedStructs, ok := getReferencedStructsRecursively(sharedStructs, otherStructs, goStructsMap)
	if !ok {
		panic("Failed to get referenced structs")
	}

	// Keep track of written Typescript types
	// This is to avoid name collisions
	writtenTypes := make(map[string]*GoStruct)

	// Group the structs by package
	structsByPackage := make(map[string][]*GoStruct)
	for _, goStruct := range referencedStructs {
		if _, ok := structsByPackage[goStruct.Package]; !ok {
			structsByPackage[goStruct.Package] = make([]*GoStruct, 0)
		}
		structsByPackage[goStruct.Package] = append(structsByPackage[goStruct.Package], goStruct)
	}

	packages := make([]string, 0)
	for k := range structsByPackage {
		packages = append(packages, k)
	}

	slices.SortStableFunc(packages, func(i, j string) int {
		return cmp.Compare(i, j)
	})

	file.WriteString("export type Nullish<T> = T | null | undefined\n\n")

	for _, pkg := range packages {

		file.WriteString("//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\n")
		file.WriteString(fmt.Sprintf("// %s\n", strings.ReplaceAll(cases.Title(language.English, cases.Compact).String(strings.ReplaceAll(pkg, "_", " ")), " ", "")))
		file.WriteString("//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\n\n")

		structs := structsByPackage[pkg]
		slices.SortStableFunc(structs, func(i, j *GoStruct) int {
			return cmp.Compare(i.FormattedName, j.FormattedName)
		})

		// Write the shared structs first
		for _, goStruct := range structs {

			writeTypescriptType(file, goStruct, writtenTypes)

		}

	}

	// Compatibility aliases for the frontend
	file.WriteString("// Compatibility aliases\n")
	file.WriteString("export type Anime_LocalFile = LocalFile\n")
	file.WriteString("export type Anime_LocalFileType = LocalFileType\n")
	file.WriteString("export type Anime_LocalFileMetadata = LocalFileMetadata\n")
	file.WriteString("export type Summary_ScanSummaryItem = ScanSummaryItem\n")
	file.WriteString("export type Summary_ScanSummaryGroup = ScanSummaryGroup\n")
	file.WriteString("export type Summary_ScanSummaryFile = ScanSummaryFile\n")
	file.WriteString("export type Summary_ScanSummary = ScanSummary\n")
	file.WriteString("export type Platform_MediaStatus = MediaStatus\n")
	file.WriteString("export type Platform_MediaFormat = MediaFormat\n")
	file.WriteString("export type Platform_UnifiedMedia = UnifiedMedia\n")
	file.WriteString("export type Platform_BaseAnime = UnifiedMedia\n")
	file.WriteString("export type Platform_UnifiedCollectionEntry = UnifiedCollectionEntry\n")

}

// getReferencedStructsRecursively returns a map of GoStructs that are referenced by the fields of sharedStructs and otherStructs.
func getReferencedStructsRecursively(sharedStructs, otherStructs []*GoStruct, goStructsMap map[string]*GoStruct) (map[string]*GoStruct, bool) {
	allStructs := make(map[string]*GoStruct)
	for _, sharedStruct := range sharedStructs {
		allStructs[sharedStruct.Package+"."+sharedStruct.Name] = sharedStruct
	}
	for _, otherStruct := range otherStructs {
		allStructs[otherStruct.Package+"."+otherStruct.Name] = otherStruct
	}

	// Keep track of the structs that have been visited

	referencedStructs := make(map[string]*GoStruct)

	for _, strct := range allStructs {
		getReferencedStructs(strct, referencedStructs, goStructsMap)
	}

	return referencedStructs, true
}

func getReferencedStructs(goStruct *GoStruct, referencedStructs map[string]*GoStruct, goStructsMap map[string]*GoStruct) {
	if _, ok := referencedStructs[goStruct.Package+"."+goStruct.Name]; ok {
		return
	}
	referencedStructs[goStruct.Package+"."+goStruct.Name] = goStruct
	for _, field := range goStruct.Fields {
		if field.JsonName == "" || !field.Public {
			continue
		}
		if field.UsedStructType != "" {
			if usedStruct, ok := goStructsMap[field.UsedStructType]; ok {
				getReferencedStructs(usedStruct, referencedStructs, goStructsMap)
			}
		}
	}
	if goStruct.AliasOf != nil {
		if usedStruct, ok := goStructsMap[goStruct.AliasOf.UsedStructType]; ok {
			getReferencedStructs(usedStruct, referencedStructs, goStructsMap)
		}
	}
}

func writeTypescriptType(f *os.File, goStruct *GoStruct, writtenTypes map[string]*GoStruct) {
	f.WriteString("/**\n")
	f.WriteString(fmt.Sprintf(" * - Filepath: %s\n", strings.TrimPrefix(goStruct.Filepath, "../")))
	f.WriteString(fmt.Sprintf(" * - Filename: %s\n", goStruct.Filename))
	f.WriteString(fmt.Sprintf(" * - Package: %s\n", goStruct.Package))
	if len(goStruct.Comments) > 0 {
		f.WriteString(" * @description\n")
		for _, cmt := range goStruct.Comments {
			f.WriteString(fmt.Sprintf(" *  %s\n", strings.TrimSpace(cmt)))
		}
	}
	f.WriteString(" */\n")

	if len(goStruct.Fields) > 0 {
		publicFieldCount := 0
		for _, field := range goStruct.Fields {
			if field.JsonName != "" && field.Public {
				publicFieldCount++
			}
		}

		if publicFieldCount > 0 {
			f.WriteString(fmt.Sprintf("export type %s = {\n", goStruct.FormattedName))
			for _, field := range goStruct.Fields {
				if field.JsonName == "" || !field.Public {
					continue
				}
				fieldNameSuffix := ""
				if !field.Required {
					fieldNameSuffix = "?"
				}

				if len(field.Comments) > 0 {
					f.WriteString("    /**\n")
					for _, cmt := range field.Comments {
						f.WriteString(fmt.Sprintf("     * %s\n", strings.TrimSpace(cmt)))
					}
					f.WriteString("     */\n")
				}

				typeText := field.TypescriptType
				typeText = strings.ReplaceAll(typeText, "RawMessage", "Record<string, any>")

				f.WriteString(fmt.Sprintf("    %s%s: %s\n", field.JsonName, fieldNameSuffix, typeText))
			}
			f.WriteString("}\n\n")
		} else if goStruct.AliasOf == nil {
			f.WriteString(fmt.Sprintf("export type %s = Record<string, never>\n\n", goStruct.FormattedName))
		}
	} else if goStruct.AliasOf == nil {
		f.WriteString(fmt.Sprintf("export type %s = Record<string, never>\n\n", goStruct.FormattedName))
	}

	if goStruct.AliasOf != nil {
		if len(goStruct.AliasOf.DeclaredValues) > 0 {
			union := ""
			if len(goStruct.AliasOf.DeclaredValues) > 5 {
				union = strings.Join(goStruct.AliasOf.DeclaredValues, " |\n    ")
			} else {
				union = strings.Join(goStruct.AliasOf.DeclaredValues, " | ")
			}
			f.WriteString(fmt.Sprintf("export type %s = %s\n\n", goStruct.FormattedName, union))
		} else {
			f.WriteString(fmt.Sprintf("export type %s = %s\n\n", goStruct.FormattedName, goStruct.AliasOf.TypescriptType))
		}
	}

	// Add the struct to the written types
	writtenTypes[goStruct.Package+"."+goStruct.Name] = goStruct
}

func getUnformattedGoType(goType string) string {
	if strings.HasPrefix(goType, "[]") {
		return getUnformattedGoType(goType[2:])
	}

	if strings.HasPrefix(goType, "*") {
		return getUnformattedGoType(goType[1:])
	}

	if strings.HasPrefix(goType, "map[") {
		s := strings.TrimPrefix(goType, "map[")
		value := ""
		for i, c := range s {
			if c == ']' {
				value = s[i+1:]
				break
			}
		}
		return getUnformattedGoType(value)
	}

	return goType
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
