import * as Lucide from "lucide-react";

export const Icons = {
  navigation: {
    home: Lucide.Home,
    tv: Lucide.Tv,
    film: Lucide.Film,
    layers: Lucide.Layers,
    rocket: Lucide.Rocket,
    settings: Lucide.Settings,
    menu: Lucide.Menu,
    chevronRight: Lucide.ChevronRight,
    chevronLeft: Lucide.ChevronLeft,
    chevronDown: Lucide.ChevronDown,
    chevronUp: Lucide.ChevronUp,
    search: Lucide.Search,
    user: Lucide.User,
    users: Lucide.Users,
    library: Lucide.Library,
    grid: Lucide.Grid,
    list: Lucide.List,
  },
  media: {
    play: Lucide.Play,
    pause: Lucide.Pause,
    stop: Lucide.Square,
    playCircle: Lucide.PlayCircle,
    forward: Lucide.FastForward,
    backward: Lucide.Rewind,
    skipNext: Lucide.SkipForward,
    skipPrevious: Lucide.SkipBack,
    volume2: Lucide.Volume2,
    volumeX: Lucide.VolumeX,
    volume1: Lucide.Volume1,
    fullscreen: Lucide.Fullscreen,
    maximize: Lucide.Maximize,
    minimize: Lucide.Minimize,
    pip: Lucide.PictureInPicture,
    cast: Lucide.Cast,
    airplay: Lucide.Airplay,
    queue: Lucide.ListVideo,
    subtitles: Lucide.Subtitles,
    gauge: Lucide.Gauge,
    repeat: Lucide.Repeat,
    wand: Lucide.Wand2,
    clapperboard: Lucide.Clapperboard,
  },
  ui: {
    close: Lucide.X,
    palette: Lucide.Palette,
    tag: Lucide.Tag,
    spinner: Lucide.Loader2,
    plus: Lucide.Plus,
    minus: Lucide.Minus,
    chevronsUpDown: Lucide.ChevronsUpDown,
    check: Lucide.Check,
    checkCircle: Lucide.CheckCircle,
    checkCircle2: Lucide.CheckCircle2,
    circle: Lucide.Circle,
    listPlus: Lucide.ListPlus,
    info: Lucide.Info,
    alert: Lucide.AlertTriangle,
    alertCircle: Lucide.AlertCircle,
    star: Lucide.Star,
    heart: Lucide.Heart,
    bookmark: Lucide.Bookmark,
    trash: Lucide.Trash2,
    download: Lucide.Download,
    upload: Lucide.Upload,
    refresh: Lucide.RefreshCw,
    rotate: Lucide.RotateCw,
    settings: Lucide.Settings,
    sliders: Lucide.SlidersHorizontal,
    filter: Lucide.Filter,
    moreHorizontal: Lucide.MoreHorizontal,
    moreVertical: Lucide.MoreVertical,
    share: Lucide.Share2,
    link: Lucide.Link,
    copy: Lucide.Copy,
    edit: Lucide.Edit,
    delete: Lucide.Trash2,
    eye: Lucide.Eye,
    eyeOff: Lucide.EyeOff,
    lock: Lucide.Lock,
    unlock: Lucide.Unlock,
    xCircle: Lucide.XCircle,
    helpCircle: Lucide.HelpCircle,
    key: Lucide.Key,
    shield: Lucide.Shield,
    bell: Lucide.Bell,
    bellOff: Lucide.BellOff,
    inbox: Lucide.Inbox,
    mail: Lucide.Mail,
    message: Lucide.MessageSquare,
    messageText: Lucide.MessageSquareText,
    send: Lucide.Send,
  },
  status: {
    sparkles: Lucide.Sparkles,
    zap: Lucide.Zap,
    trophy: Lucide.Trophy,
    skull: Lucide.Skull,
    flame: Lucide.Flame,
    gem: Lucide.Gem,
    award: Lucide.Award,
    ghost: Lucide.Ghost,
    medal: Lucide.Medal,
    crown: Lucide.Crown,
    flag: Lucide.Flag,
    target: Lucide.Target,
    trendingUp: Lucide.TrendingUp,
    trendingDown: Lucide.TrendingDown,
    activity: Lucide.Activity,
    pulse: Lucide.Activity,
    monitor: Lucide.Monitor,
    smartphone: Lucide.Smartphone,
    tablet: Lucide.Tablet,
    tv: Lucide.Tv,
    gamepad: Lucide.Gamepad2,
    headphones: Lucide.Headphones,
    music: Lucide.Music,
    musicOff: Lucide.VolumeX,
    video: Lucide.Video,
    image: Lucide.Image,
    imageOff: Lucide.ImageOff,
    file: Lucide.File,
    folder: Lucide.Folder,
    folderOpen: Lucide.FolderOpen,
    folderPlus: Lucide.FolderPlus,
    archive: Lucide.Archive,
    database: Lucide.Database,
    server: Lucide.Server,
    cloud: Lucide.Cloud,
    wifi: Lucide.Wifi,
    wifiOff: Lucide.WifiOff,
    bluetooth: Lucide.Bluetooth,
    usb: Lucide.Usb,
    hdd: Lucide.HardDrive,
    cpu: Lucide.Cpu,
    memory: Lucide.MemoryStick,
    building: Lucide.Building2,
    users2: Lucide.Users2,
    monitorPlay: Lucide.MonitorPlay,
    monitorSmartphone: Lucide.MonitorSmartphone,
    fileVideo: Lucide.FileVideo,
    radar: Lucide.Radar,
  },
  time: {
    clock: Lucide.Clock,
    timer: Lucide.Timer,
    calendar: Lucide.Calendar,
    clockAlert: Lucide.ClockAlert,
    hourglass: Lucide.Hourglass,
    sunrise: Lucide.Sunrise,
    sunset: Lucide.Sunset,
    moon: Lucide.Moon,
    sun: Lucide.Sun,
  },
  arrow: {
    up: Lucide.ArrowUp,
    down: Lucide.ArrowDown,
    left: Lucide.ArrowLeft,
    right: Lucide.ArrowRight,
    upRight: Lucide.ArrowUpRight,
    upLeft: Lucide.ArrowUpLeft,
    downRight: Lucide.ArrowDownRight,
    downLeft: Lucide.ArrowDownLeft,
    leftRight: Lucide.ArrowLeftRight,
    upDown: Lucide.ArrowUpDown,
    rotateCw: Lucide.RotateCw,
    rotateCcw: Lucide.RotateCcw,
    downUp: Lucide.ArrowDownUp,
  },
} as const;

export type IconCategory = keyof typeof Icons;
export type IconName<C extends IconCategory> = keyof typeof Icons[C];

export function getIcon<C extends IconCategory>(category: C, name: IconName<C>) {
  return Icons[category][name];
}

export default Icons;