package repository

import "kamehouse/internal/api/dragonball/domain"

func classicSeries() domain.Series {
	return domain.Series{
		ID:           "classic",
		Title:        "Dragon Ball",
		TMDBID:       12609,
		Year:         "1986–1989",
		EpisodeCount: 153,
		Canon:        true,
		Studio:       "Toei Animation",
		Description:  "La aventura original: Goku, de niño, recorre el mundo reuniendo las Esferas del Dragón, entrena en la Escuela Tortuga y madura entre torneos hasta enfrentar a Piccolo.",
		SagaIDs:      []string{"pilaf", "torneo-21", "red-ribbon", "uranai-baba", "torneo-22", "piccolo", "piccolo-jr"},
	}
}

func classicSagas() []domain.Saga {
	return []domain.Saga{
		{ID: "pilaf", SeriesID: "classic", Name: "Saga de Pilaf", StartEp: 1, EndEp: 13, Order: 1},
		{ID: "torneo-21", SeriesID: "classic", Name: "21º Torneo de Artes Marciales", StartEp: 14, EndEp: 28, Order: 2},
		{ID: "red-ribbon", SeriesID: "classic", Name: "Saga de la Patrulla Roja", StartEp: 29, EndEp: 68, Order: 3},
		{ID: "uranai-baba", SeriesID: "classic", Name: "Saga de la Abuela Baba", StartEp: 69, EndEp: 82, Order: 4},
		{ID: "torneo-22", SeriesID: "classic", Name: "22º Torneo de Artes Marciales", StartEp: 83, EndEp: 101, Order: 5},
		{ID: "piccolo", SeriesID: "classic", Name: "Saga de Piccolo Daimaoh", StartEp: 102, EndEp: 122, Order: 6},
		{ID: "piccolo-jr", SeriesID: "classic", Name: "Saga de Piccolo Jr.", StartEp: 123, EndEp: 153, Order: 7},
	}
}

func classicEpisodes() []domain.Episode {
	s := "classic"
	return []domain.Episode{
		// ── Saga de Pilaf ──
		{SeriesID: s, SagaID: "pilaf", NumberStart: 1, NumberEnd: 1, Title: "Bulma y Son Goku", Villains: []string{"Oso Ladrón"}, Milestone: "Encuentro entre Goku (12 años) y Bulma (16 años); revelación de las Esferas del Dragón."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 2, NumberEnd: 2, Title: "¡Sorpresa! ¡No hay esferas!", Milestone: "Goku protege la esfera de 4 estrellas dejada por su difunto Abuelo Gohan."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 3, NumberEnd: 3, Title: "La Nube Voladora del Maestro Roshi", Milestone: "Encuentro con el Maestro Roshi; Goku recibe la Nube Voladora (Kintoun) tras rescatar a la Tortuga Marina."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 4, NumberEnd: 4, Title: "Oolong, el demonio raptor", Villains: []string{"Oolong"}, Milestone: "Goku vence a Oolong, liberando a la aldea de sus engaños."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 5, NumberEnd: 5, Title: "Yamcha, el temible bandido del desierto", Villains: []string{"Yamcha", "Puar"}, Milestone: "Primer enfrentamiento de artes marciales entre Goku y Yamcha en el Desierto del Diablo."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 6, NumberEnd: 6, Title: "Los visitantes de medianoche", Villains: []string{"Yamcha"}, Milestone: "Yamcha padece fobia a las mujeres al ver a Bulma durmiendo."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 7, NumberEnd: 7, Title: "El Rey Gyuma del Monte Frypan", Villains: []string{"Rey Gyuma (Ox-King)"}, Milestone: "Encuentro con Milk (Chi-Chi) y el Rey Gyuma en el ardiente Monte Frypan."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 8, NumberEnd: 8, Title: "El Kamehameha del Maestro Roshi", Milestone: "El Maestro Roshi usa el Kamehameha Máximo Poder para apagar el fuego; Goku lo imita instantáneamente destruyendo un coche."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 9, NumberEnd: 9, Title: "La técnica especial de la coneja", Villains: []string{"Jefe Conejo (Monster Carrot)"}, Milestone: "Goku envía al Jefe Conejo y sus esbirros a la Luna a hacer mochis usando su Báculo Sagrado."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 10, NumberEnd: 10, Title: "¡Las Esferas del Dragón robadas!", Villains: []string{"Banda de Pilaf"}, Milestone: "Shu roba las Esferas del Dragón del grupo tras dejarlos dormidos con gas."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 11, NumberEnd: 11, Title: "¡El dragón finalmente aparece!", Villains: []string{"Banda de Pilaf"}, Milestone: "Pilaf encierra al grupo en una prisión de cristal e invoca al Dragón Shenlong."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 12, NumberEnd: 12, Title: "¡El deseo concedido!", Villains: []string{"Banda de Pilaf"}, Milestone: "Oolong interrumpe a Pilaf pidiendo el primer deseo de la franquicia (un panty femenino) frustrando la conquista mundial."},
		{SeriesID: s, SagaID: "pilaf", NumberStart: 13, NumberEnd: 13, Title: "La transformación de Goku", Villains: []string{"Banda de Pilaf"}, Milestone: "Goku observa la Luna Llena a través del techo de cristal y sufre la primera transformación en Gran Mono (Oozaru); Yamcha le corta la cola para salvar la ciudad."},

		// ── 21º Torneo de Artes Marciales ──
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 14, NumberEnd: 14, Title: "El rival de Goku: ¡Aparece Krillin!", Milestone: "Llegada de Krillin a la Kame House buscando entrenamiento marcial."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 15, NumberEnd: 15, Title: "La chica misteriosa: Launch", Milestone: "Rescate de Launch, cuya personalidad cambia entre una chica dulce y una criminal violenta al estornudar."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 16, NumberEnd: 16, Title: "La prueba de la piedra", Villains: []string{"Maestro Roshi"}, Milestone: "Prueba inicial buscando una piedra marcada en la selva."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 17, NumberEnd: 17, Title: "¡Entrenamiento de entrega de leche!", Milestone: "Métodos de la Escuela Tortuga: repartir leche a pie por las mañanas."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 18, NumberEnd: 18, Title: "¡El duro entrenamiento del Maestro Roshi!", Milestone: "Arar campos con las manos y huir de tiburones cargando caparazones pesados."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 19, NumberEnd: 19, Title: "Comienza el Tenkaichi Budokai", Milestone: "Viaje a la Capital del Sur para el 21º Torneo de Artes Marciales."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 20, NumberEnd: 20, Title: "¿Podrá el entrenamiento dar resultados?", Milestone: "Goku y Krillin superan fácilmente las eliminatorias."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 21, NumberEnd: 21, Title: "¡Peligro Krillin!", Villains: []string{"Bacterian"}, Milestone: "Krillin vence a Bacterian al recordar que carece anatómicamente de nariz."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 22, NumberEnd: 22, Title: "¡Yamcha vs. Jackie Chun!", Villains: []string{"Jackie Chun"}, Milestone: "Jackie Chun noquea a Yamcha de una sola ráfaga de aire para enseñar humildad."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 23, NumberEnd: 23, Title: "¡Aparece el temible Nam!", Villains: []string{"Ranfan", "Nam"}, Milestone: "Nam vence a Ranfan resistiendo sus distracciones coqueteras."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 24, NumberEnd: 24, Title: "La desesperada batalla de Goku", Villains: []string{"Giran"}, Milestone: "A Goku le vuelve a crecer la cola en mitad del combate y destruye la trampa de Giran."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 25, NumberEnd: 25, Title: "¡Cuidado Goku! El ataque aéreo de Nam", Villains: []string{"Nam"}, Milestone: "Goku evita el Tenku Peke-jin de Nam y lo vence; Roshi le regala a Nam agua para su aldea."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 26, NumberEnd: 26, Title: "¡La gran final! Jackie Chun vs. Goku", Villains: []string{"Jackie Chun"}, Milestone: "Inicio del combate decisivo; Goku imita las técnicas avanzadas de Roshi."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 27, NumberEnd: 27, Title: "La técnica máxima de Goku", Villains: []string{"Jackie Chun"}, Milestone: "Goku despliega la Técnica del Perro Rabioso contra Jackie Chun."},
		{SeriesID: s, SagaID: "torneo-21", NumberStart: 28, NumberEnd: 28, Title: "¡El clímax! El Kamehameha contra la Luna", Villains: []string{"Jackie Chun"}, Milestone: "Goku se transforma en Oozaru en la final; Jackie Chun destruye la Luna con un Kamehameha Máximo y gana el torneo tras un doble KO."},

		// ── Saga de la Patrulla Roja ──
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 29, NumberEnd: 29, Title: "La búsqueda solitaria: El lago flotante", Villains: []string{"Coronel Silver"}, Milestone: "Goku inicia su viaje solo para recuperar la esfera de 4 estrellas de su abuelo."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 30, NumberEnd: 30, Title: "El ataque del Coronel Silver", Villains: []string{"Coronel Silver"}, Milestone: "La Patrulla Roja destruye la Nube Voladora con un misil."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 31, NumberEnd: 31, Title: "¡Adiós, Coronel Silver!", Villains: []string{"Coronel Silver"}, Milestone: "Goku destruye la división del Coronel Silver y toma su avión espacial."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 32, NumberEnd: 32, Title: "La Torre de Fuerza en la tierra de la nieve", Villains: []string{"General White"}, Milestone: "Goku llega a la gélida aldea Jingle en la Capital del Norte y rescata a Snow."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 33, NumberEnd: 33, Title: "El temible Sargento Metálico", Villains: []string{"Sargento Metálico"}, Milestone: "Goku combate al androide Sargento Metálico en el tercer piso de la Torre de Fuerza."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 34, NumberEnd: 34, Title: "¡Batalla contra el Ninja Murasaki!", Villains: []string{"Ninja Murasaki"}, Milestone: "Enfrentamiento en el laberinto ninja con el vanidoso Ninja Murasaki."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 35, NumberEnd: 35, Title: "Las técnicas divisibles del Ninja Murasaki", Villains: []string{"Ninja Murasaki"}, Milestone: "Murasaki usa la técnica de los 5 clones (hermanos quintillizos) y Goku los vence a todos."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 36, NumberEnd: 36, Title: "El monstruo Buyon en el piso superior", Villains: []string{"Buyon"}, Milestone: "Goku congela el cuerpo de goma de Buyon rompiendo la pared de la torre para que ingrese el aire helado."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 37, NumberEnd: 37, Title: "El bondadoso Androide 8 (Octavio)", Milestone: "Goku entabla amistad con el Androide 8 (Octavio), quien se niega a pelear por tener un corazón noble."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 38, NumberEnd: 38, Title: "El ataque cobarde del General White", Villains: []string{"General White"}, Milestone: "El General White spara por la espalda al Alcalde de la aldea traicionando la negociación."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 39, NumberEnd: 39, Title: "La caída de la Torre de Fuerza", Villains: []string{"General White"}, Milestone: "Octavio enfurece al ver herido a Goku y envía al General White a volar fuera de la torre."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 40, NumberEnd: 40, Title: "Octavio y el secreto de la bomba", Milestone: "El Dr. Flappe retira la bomba destructiva del interior del pecho de Octavio."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 41, NumberEnd: 41, Title: "La selva del Capitán Yellow", Villains: []string{"Capitán Yellow"}, Milestone: "Goku viaja a la selva en búsqueda de la esfera de 3 estrellas."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 42, NumberEnd: 42, Title: "El rescate del niño Upa", Villains: []string{"Capitán Yellow"}, Milestone: "Goku salva al pequeño Upa rescatándolo del helicóptero del Capitán Yellow."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 43, NumberEnd: 43, Title: "¡Hacia la Tierra Sagrada de Karin!", Milestone: "Encuentro de Goku con el legendario guerrero Bora en la base de la Sagrada Torre de Karin."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 44, NumberEnd: 44, Title: "La cueva pirata subterránea", Villains: []string{"General Blue"}, Milestone: "Exploración de la cueva pirata bajo el océano junto a Krillin y Bulma."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 45, NumberEnd: 45, Title: "La trampa de los piratas", Villains: []string{"General Blue"}, Milestone: "El grupo evade trampas de lanzas y lava en la caverna pirata."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 46, NumberEnd: 46, Title: "El robot pirata en la oscuridad", Villains: []string{"Robot Pirata"}, Milestone: "Goku destruye al robot guardián pirata con su báculo."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 47, NumberEnd: 47, Title: "¡Escape de la cueva en colapso!", Villains: []string{"General Blue"}, Milestone: "Escape en submarino pirata justo antes del colapso de la caverna."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 48, NumberEnd: 48, Title: "La persecución del General Blue", Villains: []string{"General Blue"}, Milestone: "El General Blue persigue la nave de Goku hasta la isla del Maestro Roshi."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 49, NumberEnd: 49, Title: "El poder psíquico del General Blue", Villains: []string{"General Blue"}, Milestone: "General Blue amarra a los Guerreros Z en la Kame House mediante telequinesis."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 50, NumberEnd: 50, Title: "¡Atrapados en los poderes de Blue!", Villains: []string{"General Blue"}, Milestone: "Launch salva al grupo antes de que explote la bomba dejada por Blue."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 51, NumberEnd: 51, Title: "La huida hacia la Aldea Pingüino", Villains: []string{"General Blue"}, Milestone: "Persecución aérea de Goku tras General Blue hasta la Aldea Pingüino."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 52, NumberEnd: 52, Title: "¡Llegada a la Aldea Pingüino!", Villains: []string{"General Blue"}, Milestone: "Goku conoce a los habitantes surrealistas creados por el Dr. Senbei Norimaki."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 53, NumberEnd: 53, Title: "El encuentro con Arale Norimaki", Milestone: "Crossover con Dr. Slump: Goku se hace amigo de Arale Norimaki."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 54, NumberEnd: 54, Title: "¡Arale vs. el General Blue!", Villains: []string{"General Blue"}, Milestone: "Arale destruye el vehículo militar de Blue y lo manda a volar de un cabezazo al horizonte."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 55, NumberEnd: 55, Title: "La búsqueda en el planeta de la Luna", Villains: []string{"General Blue"}, Milestone: "Goku recupera las esferas robadas gracias a las invenciones de Senbei Norimaki."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 56, NumberEnd: 56, Title: "El regreso a la Kame House", Milestone: "Reagrupamiento en la Kame House antes de partir a la Tierra Sagrada de Karin."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 57, NumberEnd: 57, Title: "El ataque sorpresa de Blue", Villains: []string{"General Blue"}, Milestone: "General Blue es ejecutado en la sede central por la demostración de Tao Pai Pai."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 58, NumberEnd: 58, Title: "¡La llegada del Mercenario Tao Pai Pai!", Villains: []string{"Tao Pai Pai"}, Milestone: "Tao Pai Pai llega a la Tierra de Karin viajando sobre un pilar de piedra lanzado por él mismo."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 59, NumberEnd: 59, Title: "¡El asesinato de Bora!", Villains: []string{"Tao Pai Pai"}, Milestone: "Tao Pai Pai asesina despiadadamente a Bora lanzándolo al aire y atravesándolo con su propia lanza."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 60, NumberEnd: 60, Title: "¡El Dodonpa de Tao Pai Pai!", Villains: []string{"Tao Pai Pai"}, Milestone: "Goku cae derrotado ante el Dodonpa de Tao Pai Pai y decide escalar la Torre de Karin."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 61, NumberEnd: 61, Title: "La escalada a la Sagrada Torre de Karin", Milestone: "Goku escala los miles de escalones de la Sagrada Torre de Karin durante un día entero."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 62, NumberEnd: 62, Title: "El entrenamiento con el Maestro Karin", Villains: []string{"Maestro Karin"}, Milestone: "Goku intenta quitarle el frasco de Agua Sagrada al gato ermitaño Karin."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 63, NumberEnd: 63, Title: "El secreto del Agua Sagrada", Milestone: "Goku descubre que el verdadero secreto del Agua Sagrada era el esfuerzo físico de la escalada."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 64, NumberEnd: 64, Title: "¡La revancha contra Tao Pai Pai!", Villains: []string{"Tao Pai Pai"}, Milestone: "Goku destruye la espada de Tao Pai Pai y lo elimina devolviéndole su propia granada."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 65, NumberEnd: 65, Title: "El ataque a la Sede Central de la Cinta Roja", Villains: []string{"Comandante Red", "Oficial Black"}, Milestone: "Goku se infiltra en solitario destruyendo las defensas antiaéreas de la Cinta Roja."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 66, NumberEnd: 66, Title: "Goku invade la base enemiga", Villains: []string{"Oficial Black"}, Milestone: "Los soldados de la base entran en pánico al ver llegar al niño que destruyó la torre Jingle."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 67, NumberEnd: 67, Title: "El asesinato del Comandante Red", Villains: []string{"Oficial Black"}, Milestone: "El Oficial Black asesina al Comandante Red de un disparo al enterarse de que su deseo era ser más alto."},
		{SeriesID: s, SagaID: "red-ribbon", NumberStart: 68, NumberEnd: 68, Title: "¡La destrucción definitiva de la Cinta Roja!", Villains: []string{"Oficial Black"}, Milestone: "Goku destruye el mecha battle-jacket del Oficial Black erradicando a la Patrulla Roja."},

		// ── Saga de la Abuela Baba ──
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 69, NumberEnd: 69, Title: "El Palacio de la Adivina Uranai Baba", Villains: []string{"Uranai Baba"}, Milestone: "Goku y sus amigos acuden a Uranai Baba para localizar la última esfera oculta al radar."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 70, NumberEnd: 70, Title: "El combate de Krillin contra Drácula Man", Villains: []string{"Drácula Man"}, Milestone: "Drácula Man muerde la cabeza de Krillin en el coliseo flotante."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 71, NumberEnd: 71, Title: "Yamcha vs. el Hombre Invisible", Villains: []string{"El Hombre Invisible"}, Milestone: "Yamcha lucha a ciegas guiándose por el oído contra el Hombre Invisible."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 72, NumberEnd: 72, Title: "La trampa de la sangre nasal de Roshi", Villains: []string{"El Hombre Invisible"}, Milestone: "Yamcha vence al revelar la silueta del enemigo gracias a la sangre nasal desbordada de Roshi al ver a Bulma."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 73, NumberEnd: 73, Title: "La temible Momia del coliseo", Villains: []string{"La Momia"}, Milestone: "La Momia derrota a Yamcha por su descomunal fuerza bruta."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 74, NumberEnd: 74, Title: "Goku vs. La Momia", Villains: []string{"La Momia"}, Milestone: "Goku noquea a La Momia de un solo golpe al estómago."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 75, NumberEnd: 75, Title: "El rayo Akumataito del Demonio Akkuman", Villains: []string{"Akkuman (El Demonio)"}, Milestone: "Goku resiste el rayo Akumataito (que hace explotar el mal en los corazones) por su corazón puro."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 76, NumberEnd: 76, Title: "El Quinto Guerrero", Villains: []string{"El Enmascarado (Abuelo Gohan)"}, Milestone: "Goku vs. el Abuelo Gohan; el quinto guerrero enmascarado resulta ser el difunto Abuelo Gohan, regresado por 1 día del Más Allá."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 77, NumberEnd: 77, Title: "La búsqueda de la última esfera", Villains: []string{"Banda de Pilaf"}, Milestone: "Uranai Baba revela que la última esfera está guardada en un estuche blindado por Pilaf."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 78, NumberEnd: 78, Title: "El mecha gigante de la Banda de Pilaf", Villains: []string{"Banda de Pilaf"}, Milestone: "Pilaf desafía a Goku en un mecha de combate en el desierto."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 79, NumberEnd: 79, Title: "La combinación de los robots de Pilaf", Villains: []string{"Banda de Pilaf"}, Milestone: "Los robots de Pilaf, Mai y Shu se fusionan en un robot avestruz gigante."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 80, NumberEnd: 80, Title: "La derrota definitiva de Pilaf", Villains: []string{"Banda de Pilaf"}, Milestone: "Goku destruye el robot de Pilaf y recupera la esfera de 4 estrellas."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 81, NumberEnd: 81, Title: "Goku viaja al reino de los demonios", Villains: []string{"Rey Shula"}, Filler: true, Milestone: "Goku viaja al reino de los demonios para rescatar a la Princesa Misa."},
		{SeriesID: s, SagaID: "uranai-baba", NumberStart: 82, NumberEnd: 82, Title: "El monstruo InoShikaCho", Villains: []string{"Tien Shinhan", "Chaoz"}, Filler: true, Milestone: "Encuentro inicial de Goku con Tien Shinhan y Chaoz simulando cazar al monstruo InoShikaCho."},

		// ── 22º Torneo de Artes Marciales ──
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 83, NumberEnd: 83, Title: "El regreso de los guerreros tras 3 años", Villains: []string{"Maestro Tsuru", "Tien Shinhan", "Chaoz"}, Milestone: "Reencuentro en el torneo y rivalidad entre la Escuela Tortuga y la Escuela Grulla."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 84, NumberEnd: 84, Title: "Las eliminatorias del 22° Torneo", Villains: []string{"Escuela Grulla"}, Milestone: "Goku y Krillin superan sin esfuerzo las fases preliminares."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 85, NumberEnd: 85, Title: "¡Los 8 finalistas seleccionados!", Villains: []string{"Tien Shinhan", "Chaoz"}, Milestone: "Chaoz usa telequinesis para manipular la lotería de los enfrentamientos."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 86, NumberEnd: 86, Title: "Yamcha vs. Tien Shinhan", Villains: []string{"Tien Shinhan"}, Milestone: "Primer combate de cuartos de final a alta velocidad entre Yamcha y Tien."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 87, NumberEnd: 87, Title: "La crueldad de Tien Shinhan", Villains: []string{"Tien Shinhan"}, Milestone: "Tien Shinhan fractura intencionalmente la pierna de Yamcha dejándolo inconsciente."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 88, NumberEnd: 88, Title: "El duelo mental de Krillin y Chaoz", Villains: []string{"Chaoz"}, Milestone: "Chaoz usa el Dodonpa y sus poderes mentales para causar dolor de estómago a Krillin."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 89, NumberEnd: 89, Title: "La victoria matemática de Krillin", Villains: []string{"Chaoz"}, Milestone: "Krillin vence a Chaoz obligándolo a usar los dedos para resolver sumas matemáticas."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 90, NumberEnd: 90, Title: "Jackie Chun vs. el Hombre Lobo", Villains: []string{"Jackie Chun", "Man-Wolf"}, Milestone: "Jackie Chun cura la licantropía del Hombre Lobo usando la calva de Krillin como luna llena."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 91, NumberEnd: 91, Title: "Goku vs. Panputt", Villains: []string{"Panputt"}, Milestone: "Goku noquea al campeón de muay thai Panputt en tres codazos instantáneos."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 92, NumberEnd: 92, Title: "Semifinal: Jackie Chun vs. Tien Shinhan", Villains: []string{"Tien Shinhan"}, Milestone: "Jackie Chun prueba las habilidades marciales de Tien Shinhan en la semifinal."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 93, NumberEnd: 93, Title: "El retiro del Maestro Roshi", Villains: []string{"Tien Shinhan"}, Milestone: "Jackie Chun se retira aconsejando a Tien abandonar el camino de la maldad de Tsuru."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 94, NumberEnd: 94, Title: "Semifinal: Goku vs. Krillin", Milestone: "Enfrentamiento apasionado y técnico entre los dos mejores amigos de la Escuela Tortuga."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 95, NumberEnd: 95, Title: "La velocidad máxima de Goku", Milestone: "Goku le quita la cola a Krillin y clasifica a la final del torneo."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 96, NumberEnd: 96, Title: "La Gran Final: Goku vs. Tien Shinhan", Villains: []string{"Tien Shinhan"}, Milestone: "Inicio de la gran final entre Goku y Tien Shinhan."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 97, NumberEnd: 97, Title: "El choque del Taiyoken y el Kikoho", Villains: []string{"Tien Shinhan"}, Milestone: "Introducción del Taiyoken y el Bukujutsu (vuelo) por parte de Tien."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 98, NumberEnd: 98, Title: "Tien Shinhan se rebela contra Tsuru", Villains: []string{"Maestro Tsuru"}, Milestone: "Tien se niega a aprovechar la interferencia parastec de Chaoz y abandona a Tsuru."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 99, NumberEnd: 99, Title: "El Kikoho destruye la plataforma", Villains: []string{"Tien Shinhan"}, Milestone: "Tien destruye todo el cuadrilátero con un Kikoho colosal."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 100, NumberEnd: 100, Title: "El duelo en el aire", Villains: []string{"Tien Shinhan"}, Milestone: "Goku usa un Kamehameha hacia el suelo para impulsarse como un cohete contra Tien."},
		{SeriesID: s, SagaID: "torneo-22", NumberStart: 101, NumberEnd: 101, Title: "¡El campeón del 22° Torneo!", Villains: []string{"Tien Shinhan"}, Milestone: "Tien Shinhan se corona campeón al tocar suelo un segundo después que Goku (quien chocó contra un autobús)."},

		// ── Saga de Piccolo Daimaoh ──
		{SeriesID: s, SagaID: "piccolo", NumberStart: 102, NumberEnd: 102, Title: "La primera tragedia real", Villains: []string{"Tambourine"}, Milestone: "Asesinato de Krillin a manos del demonio Tambourine."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 103, NumberEnd: 103, Title: "La furia de Goku y el demonio Cymbal", Villains: []string{"Piccolo Daimaoh", "Cymbal"}, Milestone: "Piccolo Daimaoh es liberado del hervidor por Pilaf y engendra a sus sirvientes."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 104, NumberEnd: 104, Title: "Yajirobe y la esfera de 1 estrella", Villains: []string{"Cymbal"}, Milestone: "Goku conoce al guerrero glotón Yajirobe en el bosque."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 105, NumberEnd: 105, Title: "Yajirobe asesina a Cymbal", Villains: []string{"Cymbal"}, Milestone: "Yajirobe rebana a Cymbal con su katana y lo cocina en la fogata."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 106, NumberEnd: 106, Title: "Goku vs. Tambourine: La venganza", Villains: []string{"Tambourine"}, Milestone: "Goku recupera su fuerza física y busca a Tambourine."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 107, NumberEnd: 107, Title: "La destrucción del demonio Tambourine", Villains: []string{"Tambourine"}, Milestone: "Goku desintegra a Tambourine con un Kamehameha vengando a Krillin."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 108, NumberEnd: 108, Title: "La llegada del Rey Piccolo Daimaoh", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Piccolo Daimaoh desciende de su fortaleza flotante para enfrentar a Goku."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 109, NumberEnd: 109, Title: "Goku cae ante el temible Piccolo", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Piccolo Daimaoh detiene el corazón de Goku con un rayo místico dejándolo al borde de la muerte."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 110, NumberEnd: 110, Title: "El sacrificio del Maestro Roshi y el Mafuba", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Roshi muere al fallar la técnica del Mafuba para sellar a Piccolo en la olla."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 111, NumberEnd: 111, Title: "La muerte de Chaoz y el deseo de Piccolo", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Muerte de Chaoz al intentar interrumpir el deseo; Piccolo Daimaoh recupera su juventud."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 112, NumberEnd: 112, Title: "Piccolo Daimaoh asesina al Dragón Shenlong", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Piccolo destruye a Shenlong con un rayo de energía tras conceder su juventud."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 113, NumberEnd: 113, Title: "El viaje a la Torre de Karin", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Yajirobe carga a Goku herido hasta la cima de la Torre de Karin."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 114, NumberEnd: 114, Title: "Goku busca el Agua Ultra Divina", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Karin informa a Goku sobre el veneno del Agua Ultra Divina."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 115, NumberEnd: 115, Title: "La prueba mortal de la cueva helada", Villains: []string{"Guardián de la Cueva"}, Milestone: "Goku y Yajirobe superan las ilusiones de la cueva helada."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 116, NumberEnd: 116, Title: "Goku bebe el Agua Ultra Divina", Milestone: "Goku sobrevive al veneno mortal desatando todo su ki latente oculto."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 117, NumberEnd: 117, Title: "El ataque al castillo del Rey del Mundo", Villains: []string{"Piccolo Daimaoh", "Drum"}, Milestone: "Piccolo Daimaoh toma el control del gobierno mundial e inaugura el Día de Piccolo."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 118, NumberEnd: 118, Title: "Tien Shinhan intenta usar el Mafuba", Villains: []string{"Piccolo Daimaoh", "Drum"}, Milestone: "Tien Shinhan intenta sellar a Drum con el Mafuba pero el recipiente se rompe."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 119, NumberEnd: 119, Title: "Goku elimina al demonio Drum", Villains: []string{"Piccolo Daimaoh", "Drum"}, Milestone: "Goku llega a tiempo y destruye la cabeza de Drum de una sola patada."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 120, NumberEnd: 120, Title: "¡La batalla final por la Tierra!", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Inicio del enfrentamiento decisivo entre Goku renovado y Piccolo Daimaoh en su juventud."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 121, NumberEnd: 121, Title: "El Golpe del Oozaru penetrante", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Goku concentra todo su poder en su único brazo sano y atraviesa el tórax de Piccolo Daimaoh en el aire."},
		{SeriesID: s, SagaID: "piccolo", NumberStart: 122, NumberEnd: 122, Title: "El huevo de Piccolo Jr. y la victoria", Villains: []string{"Piccolo Daimaoh"}, Milestone: "Piccolo Daimaoh expulsa un huevo con su hijo reencarnado (Piccolo Jr.) segundos antes de explotar."},

		// ── Saga de Piccolo Jr. ──
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 123, NumberEnd: 123, Title: "El viaje al Templo Sagrado de Kami-sama", Milestone: "Goku usa el Báculo Sagrado para conectar la Torre de Karin con el Templo Celestial."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 124, NumberEnd: 124, Title: "Encuentro con Mr. Popo y Kami-sama", Milestone: "Goku conoce a Mr. Popo y descubre la apariencia idéntica entre Kami-sama y Piccolo Daimaoh."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 125, NumberEnd: 125, Title: "La resurrección de Shenlong y los caídos", Milestone: "Kami-sama restaura al Dragón Shenlong reviviendo al Maestro Roshi, Krillin y Chaoz."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 126, NumberEnd: 126, Title: "El entrenamiento en las alturas celestiales", Milestone: "Goku inicia 3 años de entrenamiento espiritual con Mr. Popo y Kami-sama."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 127, NumberEnd: 127, Title: "Sereno como el cielo, rápido como el rayo", Filler: true, Milestone: "Goku aprende a sentir las corrientes de aire y el ki con los ojos cerrados."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 128, NumberEnd: 128, Title: "El viaje en el tiempo de la corona", Filler: true, Milestone: "Goku viaja mentalmente al pasado para aprender serenidad de la naturaleza."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 129, NumberEnd: 129, Title: "El entrenamiento en la montaña del volcán", Filler: true, Milestone: "Goku medita en el interior de un volcán a punto de hacer erupción."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 130, NumberEnd: 130, Title: "El reencuentro tras 3 años de entrenamiento", Milestone: "Los Guerreros Z se reúnen bajo la lluvia en la sede del 23° Torneo."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 131, NumberEnd: 131, Title: "La aparición de un Goku ya adulto", Milestone: "Goku se quita el sombrero revelando que ha crecido y ahora es un joven de 18 años."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 132, NumberEnd: 132, Title: "El debut del temible Ma Junior (Piccolo Jr.)", Villains: []string{"Piccolo Jr."}, Milestone: "Piccolo Jr. ingresa al torneo bajo el seudónimo de Ma Junior."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 133, NumberEnd: 133, Title: "Eliminatorias del 23° Torneo", Villains: []string{"Piccolo Jr."}, Milestone: "Goku, Yamcha, Krillin, Tien y Piccolo superan la fase preliminar."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 134, NumberEnd: 134, Title: "Tao Pai Pai Cyborg vs. Tien Shinhan", Villains: []string{"Tao Pai Pai Cyborg"}, Milestone: "Reaparición del Mercenario Tao Pai Pai convertido en cyborg buscando venganza."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 135, NumberEnd: 135, Title: "Tien destroza las armas robóticas de Tao Pai Pai", Villains: []string{"Tao Pai Pai Cyborg"}, Milestone: "Tien rompe las armas cibernéticas de Tao Pai Pai demostrando su superación marcial."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 136, NumberEnd: 136, Title: "Goku vs. la chica misteriosa (Milk)", Milestone: "Goku combate contra la chica enmascarada sin reconocer a Milk de su infancia."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 137, NumberEnd: 137, Title: "La promesa de matrimonio con Milk", Milestone: "Goku cumple su promesa aceptando casarse con Milk tras el combate."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 138, NumberEnd: 138, Title: "Shen (Kami-sama) vs. Yamcha", Villains: []string{"Piccolo Jr."}, Milestone: "Kami-sama (poseyendo a un humano mediocre) vence a Yamcha en cuartos de final."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 139, NumberEnd: 139, Title: "Semifinal: Goku vs. Tien Shinhan", Villains: []string{"Tien Shinhan"}, Milestone: "Remake del duelo final del torneo anterior en la semifinal."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 140, NumberEnd: 140, Title: "Goku se quita 100 kg de ropa pesada", Milestone: "Goku se quita la camiseta y calzado pesados revelando su verdadera velocidad."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 141, NumberEnd: 141, Title: "Semifinal: Shen (Kami-sama) vs. Piccolo Jr.", Villains: []string{"Piccolo Jr."}, Milestone: "Enfrentamiento divino entre la mitad buena y la mitad malvada."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 142, NumberEnd: 142, Title: "Piccolo Jr. revierte el Mafuba", Villains: []string{"Piccolo Jr."}, Milestone: "Piccolo Jr. revierte el rayo del Mafuba encerrando a Kami-sama en la botella y tragándosela."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 143, NumberEnd: 143, Title: "La Gran Final: Goku vs. Piccolo Jr.", Villains: []string{"Piccolo Jr."}, Milestone: "Inicio del combate final por el destino de la Tierra."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 144, NumberEnd: 144, Title: "El combate colosal destruye el cuadrilátero", Villains: []string{"Piccolo Jr."}, Milestone: "Choque de ráfagas destructivas que reducen el cuadrilátero a escombros."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 145, NumberEnd: 145, Title: "Piccolo Jr. se transforma en Gigante", Villains: []string{"Piccolo Jr."}, Milestone: "Piccolo usa la técnica de la Súper Gigantificación multiplicando su tamaño."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 146, NumberEnd: 146, Title: "Goku rescata a Kami-sama desde las entrañas", Villains: []string{"Piccolo Jr."}, Milestone: "Goku ingresa por la garganta de Piccolo rescatando la botella con Kami-sama."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 147, NumberEnd: 147, Title: "La devastación total de la isla del torneo", Villains: []string{"Piccolo Jr."}, Milestone: "Piccolo destruye toda la isla con una onda explosiva hipergigantesca."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 148, NumberEnd: 148, Title: "Goku resulta gravemente herido de extremidades", Villains: []string{"Piccolo Jr."}, Milestone: "Piccolo rompe los brazos y piernas de Goku dejándolo inmovilizado en el suelo."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 149, NumberEnd: 149, Title: "¡El embate volador final!", Villains: []string{"Piccolo Jr."}, Milestone: "Goku usa el vuelo para impulsarse como un misil con el tórax contra Piccolo."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 150, NumberEnd: 150, Title: "¡Goku se corona Campeón del Mundo!", Milestone: "Goku cae fuera del ring sobre Piccolo ganando el Tenkaichi Budokai por primera vez."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 151, NumberEnd: 151, Title: "El perdón de Goku a Piccolo Jr.", Milestone: "Goku le entrega una semilla del ermitaño a Piccolo para salvar la vida de Kami-sama."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 152, NumberEnd: 152, Title: "La búsqueda del vestido de novia de Milk", Filler: true, Milestone: "Goku y Milk viajan al Monte Frypan a apagar el fuego místico para recuperar el vestido."},
		{SeriesID: s, SagaID: "piccolo-jr", NumberStart: 153, NumberEnd: 153, Title: "La boda de Son Goku y Milk", Filler: true, Milestone: "Goku y Milk se casan sellando la conclusión de Dragon Ball Clásico."},
	}
}
