package repository

import "kamehouse/internal/api/dragonball/domain"

func zSeries() domain.Series {
	return domain.Series{
		ID:           "z",
		Title:        "Dragon Ball Z",
		TMDBID:       12971,
		Year:         "1989–1996",
		EpisodeCount: 291,
		Canon:        true,
		Studio:       "Toei Animation",
		Description:  "La etapa adulta de Goku: el origen Saiyajin, la batalla campal en Namek contra Freezer, la amenaza de los Androides y Cell, y la saga de Majin Buu con la eclosión del Super Saiyajin.",
		SagaIDs:      []string{"saiyajin", "freezer", "garlic-jr", "androides", "cell", "torneo-otro-mundo", "gran-saiyaman", "majin-buu"},
	}
}

func zSagas() []domain.Saga {
	return []domain.Saga{
		{ID: "saiyajin", SeriesID: "z", Name: "Saga de los Saiyajins", StartEp: 1, EndEp: 35, Order: 1},
		{ID: "freezer", SeriesID: "z", Name: "Saga de Freezer", StartEp: 36, EndEp: 107, Order: 2},
		{ID: "garlic-jr", SeriesID: "z", Name: "Saga de Garlic Jr.", StartEp: 108, EndEp: 117, Order: 3},
		{ID: "androides", SeriesID: "z", Name: "Saga de los Androides", StartEp: 118, EndEp: 139, Order: 4},
		{ID: "cell", SeriesID: "z", Name: "Saga de Cell", StartEp: 140, EndEp: 194, Order: 5},
		{ID: "torneo-otro-mundo", SeriesID: "z", Name: "Saga del Torneo del Otro Mundo", StartEp: 195, EndEp: 199, Order: 6},
		{ID: "gran-saiyaman", SeriesID: "z", Name: "Saga del Gran Saiyaman", StartEp: 200, EndEp: 209, Order: 7},
		{ID: "majin-buu", SeriesID: "z", Name: "Saga de Majin Buu", StartEp: 210, EndEp: 291, Order: 8},
	}
}

func zEpisodes() []domain.Episode {
	s := "z"
	return []domain.Episode{
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 1, NumberEnd: 1, Title: "Aparece un mini-Goku, su nombre es Gohan", Villains: []string{"Raditz"}, Milestone: "Aparece un mini-Goku, su nombre es Gohan"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 2, NumberEnd: 2, Title: "Un guerrero muy fuerte con antecedentes históricos, el hermano mayor de Goku", Villains: []string{"Raditz"}, Milestone: "Un guerrero muy fuerte con antecedentes históricos, el hermano mayor de Goku"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 3, NumberEnd: 3, Title: "La combinación más fuerte de este mundo", Villains: []string{"Raditz"}, Milestone: "La combinación más fuerte de este mundo"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 4, NumberEnd: 4, Title: "¡El as bajo la manga de Piccolo! Gohan es un niño llorón", Villains: []string{"Raditz"}, Milestone: "¡El as bajo la manga de Piccolo! Gohan es un niño llorón"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 5, NumberEnd: 5, Title: "¡Goku muere! Solo hay una oportunidad", Villains: []string{"Raditz"}, Milestone: "¡Goku muere! Solo hay una oportunidad"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 6, NumberEnd: 6, Title: "Enma-sama también se sorprende. Habrá que luchar en el otro mundo", Milestone: "Goku inicia su camino por el Camino del Serpiente hacia Kaio-sama."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 7, NumberEnd: 7, Title: "Hay que sobrevivir a los dinosaurios. El duro entrenamiento de Gohan", Milestone: "Piccolo abandona a Gohan solo en el desierto para entrenar."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 8, NumberEnd: 8, Title: "Una transformación a causa del resplandor de la Luna, el poder secreto de Gohan", Milestone: "Gohan se transforma en Oozaru al mirar la luna; Piccolo destruye la luna."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 9, NumberEnd: 9, Title: "Perdóneme señor robot. Lágrimas que desaparecen en el desierto", Filler: true, Milestone: "Gohan conoce a un robot antiguo en una cueva del desierto."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 10, NumberEnd: 10, Title: "No llores Gohan. Es la primera batalla", Filler: true, Milestone: "Gohan ayuda a un dinosaurio herido."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 11, NumberEnd: 11, Title: "Los guerreros más fuertes del universo, el despertar de los Saiyajin", Villains: []string{"Príncipe Vegeta", "Nappa"}, Milestone: "Los guerreros más fuertes del universo, el despertar de los Saiyajin"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 12, NumberEnd: 12, Title: "Una pequeña siesta, Goku cae del Camino de la Serpiente", Filler: true, Milestone: "Goku cae al Infierno y enfrenta a Goz y Mez."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 13, NumberEnd: 13, Title: "¡No toques eso! La fruta secreta de Enma-sama", Filler: true, Milestone: "Goku come la fruta secreta que restaura sus energías en el Infierno."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 14, NumberEnd: 14, Title: "Una dulce tentación; la hospitalidad de la Princesa Serpiente", Filler: true, Milestone: "Goku llega al palacio de la Princesa Serpiente y logra escapar."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 15, NumberEnd: 15, Title: "¡Escapa de Piccolo! Gohan llama a una tormenta", Filler: true, Milestone: "Gohan construye una balsa e intenta regresar a casa con su madre."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 16, NumberEnd: 16, Title: "¡Corre Gohan! Milk te espera en la montaña Paozu", Filler: true, Milestone: "Gohan conoce a niños huérfanos antes de regresar con Piccolo."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 17, NumberEnd: 17, Title: "¡Una ciudad sin futuro! Un largo camino hacia la victoria", Filler: true, Milestone: "Yamcha, Tien, Krillin y Chaoz entrenan en la sala del tiempo del Templo."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 18, NumberEnd: 18, Title: "El final del Camino de la Serpiente. ¿Tú eres Kaio-sama?", Milestone: "Goku llega al planeta de Kaio-sama del Norte y conoce a Bubbles."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 19, NumberEnd: 19, Title: "¡Domina tu fuerza de gravedad! Atrapa a Bubbles", Milestone: "Goku se adapta a la gravedad 10x atrapando al mono Bubbles."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 20, NumberEnd: 20, Title: "¡La leyenda revive! Los antepasados de Goku", Milestone: "Kaio-sama cuenta la historia de los Saiyajin y Tsufurus."},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 21, NumberEnd: 21, Title: "¡Sal de ahí Shenlong! Los Saiyajin llegan a la Tierra", Villains: []string{"Príncipe Vegeta", "Nappa"}, Milestone: "¡Sal de ahí Shenlong! Los Saiyajin llegan a la Tierra"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 22, NumberEnd: 22, Title: "Inconcebible; unos Saibaimen que nacen de la tierra / ¡Yamcha muere!", Villains: []string{"Saibaiman"}, Milestone: "Inconcebible; unos Saibaimen que nacen de la tierra / ¡Yamcha muere!"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 23, NumberEnd: 23, Title: "¡Adiós Ten! La táctica de sacrificio de Chaoz y el último Kikoho", Villains: []string{"Nappa"}, Milestone: "¡Adiós Ten! La táctica de sacrificio de Chaoz y el último Kikoho"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 24, NumberEnd: 24, Title: "¡Una espera de 3 horas! La nube voladora de Goku", Villains: []string{"Nappa"}, Milestone: "¡Una espera de 3 horas! La nube voladora de Goku"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 25, NumberEnd: 25, Title: "Sacrifice (El sacrificio de Piccolo)", Villains: []string{"Nappa"}, Milestone: "Sacrifice (El sacrificio de Piccolo)"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 26, NumberEnd: 26, Title: "¡Déjenmelo a mí! La gran explosión de ira de Goku", Villains: []string{"Nappa"}, Milestone: "¡Déjenmelo a mí! La gran explosión de ira de Goku"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 27, NumberEnd: 27, Title: "El ataque de los Saiyajin", Villains: []string{"Nappa"}, Milestone: "El ataque de los Saiyajin"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 28, NumberEnd: 28, Title: "El duelo decisivo: Goku vs. Vegeta", Villains: []string{"Príncipe Vegeta"}, Milestone: "El duelo decisivo: Goku vs. Vegeta"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 29, NumberEnd: 29, Title: "¡Papá eres increíble! Una técnica mortal llamada Kaioken", Villains: []string{"Príncipe Vegeta"}, Milestone: "¡Papá eres increíble! Una técnica mortal llamada Kaioken"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 30, NumberEnd: 30, Title: "Una batalla sin límites; Goku contra Vegeta", Villains: []string{"Príncipe Vegeta"}, Milestone: "Una batalla sin límites; Goku contra Vegeta"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 31, NumberEnd: 31, Title: "¡Arriésgalo todo Goku! Una técnica final", Villains: []string{"Príncipe Vegeta"}, Milestone: "¡Arriésgalo todo Goku! Una técnica final"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 32, NumberEnd: 32, Title: "¡Un poder de combate de 10 veces más! La gran transformación de Vegeta", Villains: []string{"Vegeta Oozaru"}, Milestone: "¡Un poder de combate de 10 veces más! La gran transformación de Vegeta"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 33, NumberEnd: 33, Title: "¡No te mueras papá! El poder de Gohan", Villains: []string{"Vegeta Oozaru"}, Milestone: "¡No te mueras papá! El poder de Gohan"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 34, NumberEnd: 34, Title: "¡Dispara Krillin! La Genkidama de la esperanza", Villains: []string{"Príncipe Vegeta"}, Milestone: "¡Dispara Krillin! La Genkidama de la esperanza"},
		{SeriesID: s, SagaID: "saiyajin", NumberStart: 35, NumberEnd: 35, Title: "¡Ocurre un milagro! La transformación de Gohan", Villains: []string{"Príncipe Vegeta"}, Milestone: "¡Ocurre un milagro! La transformación de Gohan"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 36, NumberEnd: 36, Title: "Rumbo al planeta Namek", Milestone: "Descubrimiento de la nave Namekiana de Kami-sama en la Tierra."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 37, NumberEnd: 37, Title: "El misterioso planeta Yunzabit", Milestone: "Mr. Popo y Bulma prueban la nave en las alturas de Yunzabit."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 38, NumberEnd: 38, Title: "¡Despegue hacia Namek!", Milestone: "Bulma, Krillin y Gohan despegan al espacio rumbo al planeta Namek."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 39, NumberEnd: 39, Title: "Amigos o enemigos", Filler: true, Milestone: "Los guerreros llegan al falso Namekusei y son engañados por ilusiones."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 40, NumberEnd: 40, Title: "Peligro en el falso Namek", Filler: true, Milestone: "Bulma, Krillin y Gohan descubren la farsa y escapan del planeta ilusión."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 41, NumberEnd: 41, Title: "El falso planeta Namek", Filler: true, Milestone: "El grupo se desvía aterizando en un planeta ilusorio creado por niños huérfanos."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 42, NumberEnd: 42, Title: "Peligro en la niebla", Filler: true, Milestone: "Escape de la nave del falso Namek."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 43, NumberEnd: 43, Title: "La llegada de los villanos", Villains: []string{"Freezer 1ª Forma", "Cui"}, Milestone: "La llegada de los villanos"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 44, NumberEnd: 44, Title: "Cui vs. Vegeta", Villains: []string{"Cui"}, Milestone: "Cui vs. Vegeta"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 45, NumberEnd: 45, Title: "Las esferas en peligro", Villains: []string{"Freezer 1ª Forma", "Zarbon", "Dodoria"}, Milestone: "Las esferas en peligro"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 46, NumberEnd: 46, Title: "¡Un nuevo enemigo!", Villains: []string{"Dodoria"}, Milestone: "¡Un nuevo enemigo!"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 47, NumberEnd: 47, Title: "El rescate de Dende", Villains: []string{"Dodoria"}, Milestone: "El rescate de Dende"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 48, NumberEnd: 48, Title: "La muerte de Dodoria", Villains: []string{"Dodoria"}, Milestone: "La muerte de Dodoria"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 49, NumberEnd: 49, Title: "La emboscada namekiana", Villains: []string{"Freezer 1ª Forma"}, Milestone: "La emboscada namekiana"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 50, NumberEnd: 50, Title: "Vegeta encuentra la esfera de 4 estrellas", Villains: []string{"Zarbon"}, Milestone: "Vegeta encuentra la esfera de 4 estrellas"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 51, NumberEnd: 51, Title: "La transformación de Zarbon", Villains: []string{"Zarbon Monster"}, Milestone: "La transformación de Zarbon"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 52, NumberEnd: 52, Title: "La recuperación de Vegeta", Villains: []string{"Freezer 1ª Forma"}, Milestone: "La recuperación de Vegeta"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 53, NumberEnd: 53, Title: "El robo de las 5 esferas", Villains: []string{"Freezer 1ª Forma"}, Milestone: "El robo de las 5 esferas"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 54, NumberEnd: 54, Title: "La revancha contra Zarbon", Villains: []string{"Zarbon Monster"}, Milestone: "La revancha contra Zarbon"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 55, NumberEnd: 55, Title: "El desbloqueo del poder de Gohan", Milestone: "El Gran Patriarca despierta el ki oculto de Gohan y Krillin."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 56, NumberEnd: 56, Title: "La llamada a las Fuerzas Especiales Ginyu", Villains: []string{"Freezer 1ª Forma"}, Milestone: "La llamada a las Fuerzas Especiales Ginyu"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 57, NumberEnd: 57, Title: "La cura milagrosa en la nave", Filler: true, Milestone: "Goku llega casi al límite de su capacidad en la gravedad 100x pero se cura con Semillas del Ermitaño."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 58, NumberEnd: 58, Title: "¡Las Fuerzas Ginyu aterrizan!", Villains: []string{"Fuerzas Especiales Ginyu"}, Milestone: "¡Las Fuerzas Ginyu aterrizan!"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 59, NumberEnd: 59, Title: "La velocidad de Guldo", Villains: []string{"Guldo"}, Milestone: "La velocidad de Guldo"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 60, NumberEnd: 60, Title: "Vegeta decapita a Guldo", Villains: []string{"Guldo"}, Milestone: "Vegeta decapita a Guldo"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 61, NumberEnd: 61, Title: "La ferocidad de Recoome", Villains: []string{"Recoome"}, Milestone: "La ferocidad de Recoome"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 62, NumberEnd: 62, Title: "¡Goku aterriza en Namek!", Villains: []string{"Recoome"}, Milestone: "¡Goku aterriza en Namek!"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 63, NumberEnd: 63, Title: "Goku noquea a Recoome", Villains: []string{"Recoome"}, Milestone: "Goku noquea a Recoome"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 64, NumberEnd: 64, Title: "Burter y Jeice al ataque", Villains: []string{"Burter", "Jeice"}, Milestone: "Burter y Jeice al ataque"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 65, NumberEnd: 65, Title: "El fin de Burter y Jeice", Villains: []string{"Burter", "Jeice"}, Milestone: "El fin de Burter y Jeice"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 66, NumberEnd: 66, Title: "Capitán Ginyu entra en acción", Villains: []string{"Capitán Ginyu"}, Milestone: "Capitán Ginyu entra en acción"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 67, NumberEnd: 67, Title: "¡Cambio de cuerpo!", Villains: []string{"Capitán Ginyu"}, Milestone: "¡Cambio de cuerpo!"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 68, NumberEnd: 68, Title: "Ginyu en el cuerpo de Goku", Villains: []string{"Capitán Ginyu"}, Milestone: "Ginyu en el cuerpo de Goku"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 69, NumberEnd: 69, Title: "Ginyu se convierte en rana", Villains: []string{"Capitán Ginyu"}, Milestone: "Ginyu se convierte en rana"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 70, NumberEnd: 70, Title: "Nail defiende al Gran Patriarca", Villains: []string{"Freezer 1ª Forma"}, Milestone: "Nail defiende al Gran Patriarca"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 71, NumberEnd: 71, Title: "Invocación a Porunga", Milestone: "Dende invoca a Porunga en namekiano concediendo los dos primeros deseos."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 72, NumberEnd: 72, Title: "La resurrección de Piccolo", Milestone: "Porunga revive a Piccolo y lo transporta al planeta Namek."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 73, NumberEnd: 73, Title: "La fusión de Piccolo y Nail", Milestone: "Piccolo se fusiona mediante asimilación namekiana con Nail moribundo."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 74, NumberEnd: 74, Title: "¡La llegada del Emperador!", Villains: []string{"Freezer 1ª Forma"}, Milestone: "¡La llegada del Emperador!"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 75, NumberEnd: 75, Title: "La transformación en 2ª Forma", Villains: []string{"Freezer 2ª Forma"}, Milestone: "La transformación en 2ª Forma"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 76, NumberEnd: 76, Title: "Freezer atraviesa a Krillin", Villains: []string{"Freezer 2ª Forma"}, Milestone: "Freezer atraviesa a Krillin"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 77, NumberEnd: 77, Title: "La furia de Gohan", Villains: []string{"Freezer 2ª Forma"}, Milestone: "La furia de Gohan"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 78, NumberEnd: 78, Title: "La llegada de Piccolo Asimilado", Villains: []string{"Freezer 2ª Forma"}, Milestone: "La llegada de Piccolo Asimilado"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 79, NumberEnd: 79, Title: "La horripilante 3ª Forma", Villains: []string{"Freezer 3ª Forma"}, Milestone: "La horripilante 3ª Forma"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 80, NumberEnd: 80, Title: "La Transformación Final de Freezer", Villains: []string{"Freezer Forma Final"}, Milestone: "La Transformación Final de Freezer"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 81, NumberEnd: 81, Title: "Vegeta busca el poder Saiyajin", Villains: []string{"Freezer Forma Final"}, Milestone: "Vegeta busca el poder Saiyajin"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 82, NumberEnd: 82, Title: "Muerte de Dende", Villains: []string{"Freezer Forma Final"}, Milestone: "Muerte de Dende"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 83, NumberEnd: 83, Title: "La desesperación de Vegeta", Villains: []string{"Freezer Forma Final"}, Milestone: "La desesperación de Vegeta"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 84, NumberEnd: 84, Title: "Goku sale de la cápsula médica", Villains: []string{"Freezer Forma Final"}, Milestone: "Goku sale de la cápsula médica"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 85, NumberEnd: 85, Title: "La muerte de Vegeta", Villains: []string{"Freezer Forma Final"}, Milestone: "La muerte de Vegeta"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 86, NumberEnd: 86, Title: "Goku vs. Freezer", Villains: []string{"Freezer Forma Final"}, Milestone: "Goku vs. Freezer"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 87, NumberEnd: 87, Title: "El combate bajo el agua", Villains: []string{"Freezer Forma Final"}, Milestone: "El combate bajo el agua"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 88, NumberEnd: 88, Title: "Freezer usa el 50% de su poder", Villains: []string{"Freezer Forma Final"}, Milestone: "Freezer usa el 50% de su poder"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 89, NumberEnd: 89, Title: "El Kaioken multiplicado por 20", Villains: []string{"Freezer Forma Final"}, Milestone: "El Kaioken multiplicado por 20"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 90, NumberEnd: 90, Title: "La Genkidama de Namek", Villains: []string{"Freezer Forma Final"}, Milestone: "La Genkidama de Namek"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 91, NumberEnd: 91, Title: "Piccolo distrae a Freezer", Villains: []string{"Freezer Forma Final"}, Milestone: "Piccolo distrae a Freezer"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 92, NumberEnd: 92, Title: "La caída de la Genkidama", Villains: []string{"Freezer Forma Final"}, Milestone: "La caída de la Genkidama"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 93, NumberEnd: 93, Title: "La falsa victoria", Villains: []string{"Freezer Forma Final"}, Milestone: "La falsa victoria"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 94, NumberEnd: 94, Title: "La explosión de Krillin", Villains: []string{"Freezer Forma Final"}, Milestone: "La explosión de Krillin"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 95, NumberEnd: 95, Title: "El Despertar del Super Saiyajin", Villains: []string{"Freezer Forma Final"}, Milestone: "El Despertar del Super Saiyajin"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 96, NumberEnd: 96, Title: "El poder del Super Saiyajin", Villains: []string{"Freezer Forma Final"}, Milestone: "El poder del Super Saiyajin"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 97, NumberEnd: 97, Title: "Freezer al 100% de su poder", Villains: []string{"Freezer 100% Poder"}, Milestone: "Freezer al 100% de su poder"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 98, NumberEnd: 98, Title: "La cuenta regresiva de 5 minutos", Villains: []string{"Freezer 100% Poder"}, Milestone: "La cuenta regresiva de 5 minutos"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 99, NumberEnd: 99, Title: "El deseo en la Tierra", Milestone: "Kami-sama revive a todos los asesinados por Freezer y sus hombres usando a Shenlong."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 100, NumberEnd: 100, Title: "La evacuación masiva a la Tierra", Milestone: "Porunga transporta a todos los Namekianos, Gohan, Piccolo y Bulma a la Tierra, excepto a Goku y Freezer."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 101, NumberEnd: 101, Title: "Goku vs. Freezer: El clímax", Villains: []string{"Freezer 100% Poder"}, Milestone: "Goku vs. Freezer: El clímax"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 102, NumberEnd: 102, Title: "La falla del ki de Freezer", Villains: []string{"Freezer 100% Poder"}, Milestone: "La falla del ki de Freezer"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 103, NumberEnd: 103, Title: "Los Kizan cortantes", Villains: []string{"Freezer 100% Poder"}, Milestone: "Los Kizan cortantes"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 104, NumberEnd: 104, Title: "La piedad de Goku", Villains: []string{"Freezer 100% Poder"}, Milestone: "La piedad de Goku"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 105, NumberEnd: 105, Title: "¡Estúpido!", Villains: []string{"Freezer 100% Poder"}, Milestone: "¡Estúpido!"},
		{SeriesID: s, SagaID: "freezer", NumberStart: 106, NumberEnd: 106, Title: "La explosión del Planeta Namek", Milestone: "El Planeta Namek explota; la nave de Freezer no arranca y Goku desaparece en la explosión."},
		{SeriesID: s, SagaID: "freezer", NumberStart: 107, NumberEnd: 107, Title: "Los Guerreros Z resucitan", Milestone: "Porunga resucita a los caídos y revela que Goku sigue con vida en el espacio."},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 108, NumberEnd: 108, Title: "La neblina del mal", Villains: []string{"Garlic Jr."}, Milestone: "La neblina del mal"},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 109, NumberEnd: 109, Title: "Los Cuatro Reyes del Mal", Villains: []string{"Cuatro Reyes del Mal"}, Milestone: "Los Cuatro Reyes del Mal"},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 110, NumberEnd: 110, Title: "La batalla en el Templo Sagrado", Villains: []string{"Garlic Jr."}, Milestone: "La batalla en el Templo Sagrado"},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 111, NumberEnd: 111, Title: "La liberación de Kami-sama", Villains: []string{"Garlic Jr."}, Milestone: "La liberación de Kami-sama"},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 112, NumberEnd: 112, Title: "La Estrella Makyo", Villains: []string{"Garlic Jr."}, Milestone: "La Estrella Makyo"},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 113, NumberEnd: 113, Title: "La reapertura de la Zona Muerta", Villains: []string{"Garlic Jr."}, Milestone: "La reapertura de la Zona Muerta"},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 114, NumberEnd: 114, Title: "La destrucción de la Estrella Makyo", Villains: []string{"Garlic Jr."}, Milestone: "La destrucción de la Estrella Makyo"},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 115, NumberEnd: 115, Title: "La paz regresa a la Tierra", Filler: true, Milestone: "Purificación completa de la población de la Tierra."},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 116, NumberEnd: 116, Title: "El viaje en busca de Goku", Filler: true, Milestone: "Vegeta viaja en nave por el espacio buscando rastros de Goku."},
		{SeriesID: s, SagaID: "garlic-jr", NumberStart: 117, NumberEnd: 117, Title: "La propuesta de Krillin", Filler: true, Milestone: "Krillin decide no comprometerse con Maron al comprender sus diferencias."},
		{SeriesID: s, SagaID: "androides", NumberStart: 118, NumberEnd: 118, Title: "La llegada de Mecha Freezer", Villains: []string{"Mecha Freezer", "King Cold"}, Milestone: "La llegada de Mecha Freezer"},
		{SeriesID: s, SagaID: "androides", NumberStart: 119, NumberEnd: 119, Title: "El misterioso joven del futuro", Villains: []string{"Mecha Freezer"}, Milestone: "El misterioso joven del futuro"},
		{SeriesID: s, SagaID: "androides", NumberStart: 120, NumberEnd: 120, Title: "Trunks se transforma en Super Saiyajin", Villains: []string{"Mecha Freezer"}, Milestone: "Trunks se transforma en Super Saiyajin"},
		{SeriesID: s, SagaID: "androides", NumberStart: 121, NumberEnd: 121, Title: "La muerte de King Cold", Villains: []string{"King Cold"}, Milestone: "La muerte de King Cold"},
		{SeriesID: s, SagaID: "androides", NumberStart: 122, NumberEnd: 122, Title: "El regreso de Son Goku", Milestone: "Goku aterriza en su cápsula espacial de la Fuerza Ginyu procedente del Planeta Yadrat."},
		{SeriesID: s, SagaID: "androides", NumberStart: 123, NumberEnd: 123, Title: "La técnica de la Teletransportación", Milestone: "Goku demuestra la Teletransportación (Shunkan Ido) aprendida en Yadrat."},
		{SeriesID: s, SagaID: "androides", NumberStart: 124, NumberEnd: 124, Title: "La advertencia del virus del corazón", Milestone: "Trunks advierte sobre la enfermedad del corazón de Goku y la llegada de los Androides en 3 años."},
		{SeriesID: s, SagaID: "androides", NumberStart: 125, NumberEnd: 125, Title: "El entrenamiento de la licencia de conducir", Filler: true, Milestone: "Goku y Piccolo toman clases cómicas para sacar la licencia de conducir a petición de Milk."},
		{SeriesID: s, SagaID: "androides", NumberStart: 126, NumberEnd: 126, Title: "La fecha señalada: 12 de mayo", Villains: []string{"Androide 19", "Dr. Gero (Androide 20)"}, Milestone: "La fecha señalada: 12 de mayo"},
		{SeriesID: s, SagaID: "androides", NumberStart: 127, NumberEnd: 127, Title: "Goku vs. Androide 19", Villains: []string{"Androide 19"}, Milestone: "Goku vs. Androide 19"},
		{SeriesID: s, SagaID: "androides", NumberStart: 128, NumberEnd: 128, Title: "El ataque al corazón de Goku", Villains: []string{"Androide 19"}, Milestone: "El ataque al corazón de Goku"},
		{SeriesID: s, SagaID: "androides", NumberStart: 129, NumberEnd: 129, Title: "Vegeta se transforma en Super Saiyajin", Villains: []string{"Androide 19"}, Milestone: "Vegeta se transforma en Super Saiyajin"},
		{SeriesID: s, SagaID: "androides", NumberStart: 130, NumberEnd: 130, Title: "El Big Bang Attack", Villains: []string{"Androide 19"}, Milestone: "El Big Bang Attack"},
		{SeriesID: s, SagaID: "androides", NumberStart: 131, NumberEnd: 131, Title: "La huida del Dr. Gero", Villains: []string{"Dr. Gero (Androide 20)"}, Milestone: "La huida del Dr. Gero"},
		{SeriesID: s, SagaID: "androides", NumberStart: 132, NumberEnd: 132, Title: "La búsqueda del laboratorio secreto", Villains: []string{"Dr. Gero (Androide 20)"}, Milestone: "La búsqueda del laboratorio secreto"},
		{SeriesID: s, SagaID: "androides", NumberStart: 133, NumberEnd: 133, Title: "El despertar de Androide 17 y 18", Villains: []string{"Androide 17", "Androide 18"}, Milestone: "El despertar de Androide 17 y 18"},
		{SeriesID: s, SagaID: "androides", NumberStart: 134, NumberEnd: 134, Title: "La muerte del Dr. Gero", Villains: []string{"Androide 17"}, Milestone: "La muerte del Dr. Gero"},
		{SeriesID: s, SagaID: "androides", NumberStart: 135, NumberEnd: 135, Title: "El despertar de Androide 16", Villains: []string{"Androide 16"}, Milestone: "El despertar de Androide 16"},
		{SeriesID: s, SagaID: "androides", NumberStart: 136, NumberEnd: 136, Title: "Vegeta vs. Androide 18", Villains: []string{"Androide 18"}, Milestone: "Vegeta vs. Androide 18"},
		{SeriesID: s, SagaID: "androides", NumberStart: 137, NumberEnd: 137, Title: "La derrota total de los Z Warriors", Villains: []string{"Androide 17", "Androide 18"}, Milestone: "La derrota total de los Z Warriors"},
		{SeriesID: s, SagaID: "androides", NumberStart: 138, NumberEnd: 138, Title: "La decisión de Piccolo", Milestone: "Piccolo vuela al Templo para proponerle la fusión namekiana definitiva a Kami-sama."},
		{SeriesID: s, SagaID: "androides", NumberStart: 139, NumberEnd: 139, Title: "El descubrimiento de la máquina del tiempo", Milestone: "Bulma encuentra la segunda máquina del tiempo abandonada e infectada con una cáscara de huevo gigante."},
		{SeriesID: s, SagaID: "cell", NumberStart: 140, NumberEnd: 140, Title: "El nacimiento de un monstruo", Villains: []string{"Cell Imperfecto"}, Milestone: "El nacimiento de un monstruo"},
		{SeriesID: s, SagaID: "cell", NumberStart: 141, NumberEnd: 141, Title: "La fusión de Piccolo y Kami-sama", Villains: []string{"Cell Imperfecto"}, Milestone: "La fusión de Piccolo y Kami-sama"},
		{SeriesID: s, SagaID: "cell", NumberStart: 142, NumberEnd: 142, Title: "Encuentro en la ciudad Ginger", Villains: []string{"Cell Imperfecto"}, Milestone: "Encuentro en la ciudad Ginger"},
		{SeriesID: s, SagaID: "cell", NumberStart: 143, NumberEnd: 143, Title: "La revelación de la Biología de Cell", Villains: []string{"Cell Imperfecto"}, Milestone: "La revelación de la Biología de Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 144, NumberEnd: 144, Title: "El escape de Cell", Villains: []string{"Cell Imperfecto"}, Milestone: "El escape de Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 145, NumberEnd: 145, Title: "El secreto del laboratorio subterráneo", Milestone: "Trunks y Krillin destruyen la computadora central del laboratorio bajo tierra y consiguen los planos de A17."},
		{SeriesID: s, SagaID: "cell", NumberStart: 146, NumberEnd: 146, Title: "La recuperación completa de Goku", Milestone: "Goku despierta totalmente curado tras tomar la medicina del corazón."},
		{SeriesID: s, SagaID: "cell", NumberStart: 147, NumberEnd: 147, Title: "Entrenamiento en la Sala del Tiempo", Milestone: "Goku lleva a Vegeta, Trunks y Gohan a la Habitación del Tiempo en el Templo Sagrado."},
		{SeriesID: s, SagaID: "cell", NumberStart: 148, NumberEnd: 148, Title: "Piccolo vs. Androide 17", Villains: []string{"Androide 17"}, Milestone: "Piccolo vs. Androide 17"},
		{SeriesID: s, SagaID: "cell", NumberStart: 149, NumberEnd: 149, Title: "Cell localiza a los androides", Villains: []string{"Cell Imperfecto"}, Milestone: "Cell localiza a los androides"},
		{SeriesID: s, SagaID: "cell", NumberStart: 150, NumberEnd: 150, Title: "La intervención del Androide 16", Villains: []string{"Cell Imperfecto"}, Milestone: "La intervención del Androide 16"},
		{SeriesID: s, SagaID: "cell", NumberStart: 151, NumberEnd: 151, Title: "La absorción de Androide 17", Villains: []string{"Cell Semiperfecto"}, Milestone: "La absorción de Androide 17"},
		{SeriesID: s, SagaID: "cell", NumberStart: 152, NumberEnd: 152, Title: "El sacrificio de Tien y el Shin Kikoho", Villains: []string{"Cell Semiperfecto"}, Milestone: "El sacrificio de Tien y el Shin Kikoho"},
		{SeriesID: s, SagaID: "cell", NumberStart: 153, NumberEnd: 153, Title: "Goku rescata a Tien y Piccolo", Villains: []string{"Cell Semiperfecto"}, Milestone: "Goku rescata a Tien y Piccolo"},
		{SeriesID: s, SagaID: "cell", NumberStart: 154, NumberEnd: 154, Title: "Súper Vegeta entra en combate", Villains: []string{"Cell Semiperfecto"}, Milestone: "Súper Vegeta entra en combate"},
		{SeriesID: s, SagaID: "cell", NumberStart: 155, NumberEnd: 155, Title: "La humillación de Cell Semiperfecto", Villains: []string{"Cell Semiperfecto"}, Milestone: "La humillación de Cell Semiperfecto"},
		{SeriesID: s, SagaID: "cell", NumberStart: 156, NumberEnd: 156, Title: "El orgullo de Vegeta permite el engaño", Villains: []string{"Cell Semiperfecto"}, Milestone: "El orgullo de Vegeta permite el engaño"},
		{SeriesID: s, SagaID: "cell", NumberStart: 157, NumberEnd: 157, Title: "Trunks intenta detener a Cell", Villains: []string{"Cell Semiperfecto"}, Milestone: "Trunks intenta detener a Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 158, NumberEnd: 158, Title: "Krillin destruye el control remoto", Milestone: "Krillin rompe el control de apagado al no poder destruir a A18 por amor."},
		{SeriesID: s, SagaID: "cell", NumberStart: 159, NumberEnd: 159, Title: "El nacimiento de Cell Perfecto", Villains: []string{"Cell Perfecto"}, Milestone: "El nacimiento de Cell Perfecto"},
		{SeriesID: s, SagaID: "cell", NumberStart: 160, NumberEnd: 160, Title: "El verdadero poder de Cell Perfecto", Villains: []string{"Cell Perfecto"}, Milestone: "El verdadero poder de Cell Perfecto"},
		{SeriesID: s, SagaID: "cell", NumberStart: 161, NumberEnd: 161, Title: "El Final Flash de Vegeta", Villains: []string{"Cell Perfecto"}, Milestone: "El Final Flash de Vegeta"},
		{SeriesID: s, SagaID: "cell", NumberStart: 162, NumberEnd: 162, Title: "Trunks Super Saiyajin Dai San Stage", Villains: []string{"Cell Perfecto"}, Milestone: "Trunks Super Saiyajin Dai San Stage"},
		{SeriesID: s, SagaID: "cell", NumberStart: 163, NumberEnd: 163, Title: "El error de la musculatura extrema", Villains: []string{"Cell Perfecto"}, Milestone: "El error de la musculatura extrema"},
		{SeriesID: s, SagaID: "cell", NumberStart: 164, NumberEnd: 164, Title: "El anuncio de los Juegos de Cell", Villains: []string{"Cell Perfecto"}, Milestone: "El anuncio de los Juegos de Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 165, NumberEnd: 165, Title: "Goku y Gohan salen de la sala", Milestone: "Goku y Gohan completan su entrenamiento permaneciendo en SSJ1 Full Power en todo momento."},
		{SeriesID: s, SagaID: "cell", NumberStart: 166, NumberEnd: 166, Title: "La transmisión televisiva de Cell", Villains: []string{"Cell Perfecto"}, Milestone: "La transmisión televisiva de Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 167, NumberEnd: 167, Title: "El descanso de 9 días", Milestone: "Goku decide pasar los 9 días descansando pacíficamente con su familia."},
		{SeriesID: s, SagaID: "cell", NumberStart: 168, NumberEnd: 168, Title: "La búsqueda de un nuevo Kami-sama", Milestone: "Goku viaja al nuevo planeta Namek para traer a Dende como nuevo Dios de la Tierra."},
		{SeriesID: s, SagaID: "cell", NumberStart: 169, NumberEnd: 169, Title: "Dende reactiva las Esferas del Dragón", Milestone: "Dende recrea a Shenlong concediendo 2 deseos por invocación."},
		{SeriesID: s, SagaID: "cell", NumberStart: 170, NumberEnd: 170, Title: "Mr. Satán entra en escena", Milestone: "Presentación del campeón mundial de artes marciales humanas Mr. Satán."},
		{SeriesID: s, SagaID: "cell", NumberStart: 171, NumberEnd: 171, Title: "El recuerdo del cumpleaños de Gohan", Filler: true, Milestone: "Flashback de la infancia de Gohan celebrando sus 11 años."},
		{SeriesID: s, SagaID: "cell", NumberStart: 172, NumberEnd: 172, Title: "El ejército ataca a Cell", Villains: []string{"Cell Perfecto"}, Milestone: "El ejército ataca a Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 173, NumberEnd: 173, Title: "El inicio de los Juegos de Cell", Villains: []string{"Cell Perfecto"}, Milestone: "El inicio de los Juegos de Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 174, NumberEnd: 174, Title: "Mr. Satán vs. Cell", Villains: []string{"Cell Perfecto"}, Milestone: "Mr. Satán vs. Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 175, NumberEnd: 175, Title: "Goku vs. Cell: El primer combate", Villains: []string{"Cell Perfecto"}, Milestone: "Goku vs. Cell: El primer combate"},
		{SeriesID: s, SagaID: "cell", NumberStart: 176, NumberEnd: 176, Title: "El choque de las técnicas copiadas", Villains: []string{"Cell Perfecto"}, Milestone: "El choque de las técnicas copiadas"},
		{SeriesID: s, SagaID: "cell", NumberStart: 177, NumberEnd: 177, Title: "Cell destruye la plataforma", Villains: []string{"Cell Perfecto"}, Milestone: "Cell destruye la plataforma"},
		{SeriesID: s, SagaID: "cell", NumberStart: 178, NumberEnd: 178, Title: "El Instant Kamehameha de Goku", Villains: []string{"Cell Perfecto"}, Milestone: "El Instant Kamehameha de Goku"},
		{SeriesID: s, SagaID: "cell", NumberStart: 179, NumberEnd: 179, Title: "La rendición de Son Goku", Villains: []string{"Cell Perfecto"}, Milestone: "La rendición de Son Goku"},
		{SeriesID: s, SagaID: "cell", NumberStart: 180, NumberEnd: 180, Title: "Gohan entra al cuadrilátero", Villains: []string{"Cell Perfecto"}, Milestone: "Gohan entra al cuadrilátero"},
		{SeriesID: s, SagaID: "cell", NumberStart: 181, NumberEnd: 181, Title: "La furia oculta de Gohan", Villains: []string{"Cell Perfecto"}, Milestone: "La furia oculta de Gohan"},
		{SeriesID: s, SagaID: "cell", NumberStart: 182, NumberEnd: 182, Title: "Los Cell Juniors al ataque", Villains: []string{"Cell Juniors"}, Milestone: "Los Cell Juniors al ataque"},
		{SeriesID: s, SagaID: "cell", NumberStart: 183, NumberEnd: 183, Title: "La agonía de los Guerreros Z", Villains: []string{"Cell Juniors"}, Milestone: "La agonía de los Guerreros Z"},
		{SeriesID: s, SagaID: "cell", NumberStart: 184, NumberEnd: 184, Title: "Despertar del Super Saiyajin 2", Villains: []string{"Cell Perfecto"}, Milestone: "Despertar del Super Saiyajin 2"},
		{SeriesID: s, SagaID: "cell", NumberStart: 185, NumberEnd: 185, Title: "Gohan masacra a los Cell Juniors", Villains: []string{"Cell Juniors"}, Milestone: "Gohan masacra a los Cell Juniors"},
		{SeriesID: s, SagaID: "cell", NumberStart: 186, NumberEnd: 186, Title: "La humillación de Cell Perfecto", Villains: []string{"Cell Perfecto"}, Milestone: "La humillación de Cell Perfecto"},
		{SeriesID: s, SagaID: "cell", NumberStart: 187, NumberEnd: 187, Title: "La autodestrucción de Cell", Villains: []string{"Cell Semiperfecto"}, Milestone: "La autodestrucción de Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 188, NumberEnd: 188, Title: "El Sacrificio de Goku ante Cell", Villains: []string{"Cell Semiperfecto"}, Milestone: "El Sacrificio de Goku ante Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 189, NumberEnd: 189, Title: "El retorno de Cell Super Perfecto", Villains: []string{"Cell Super Perfecto"}, Milestone: "El retorno de Cell Super Perfecto"},
		{SeriesID: s, SagaID: "cell", NumberStart: 190, NumberEnd: 190, Title: "La muerte de Trunks del Futuro", Villains: []string{"Cell Super Perfecto"}, Milestone: "La muerte de Trunks del Futuro"},
		{SeriesID: s, SagaID: "cell", NumberStart: 191, NumberEnd: 191, Title: "El choque del Padre e Hijo Kamehameha", Villains: []string{"Cell Super Perfecto"}, Milestone: "El choque del Padre e Hijo Kamehameha"},
		{SeriesID: s, SagaID: "cell", NumberStart: 192, NumberEnd: 192, Title: "La desintegración total de Cell", Villains: []string{"Cell Super Perfecto"}, Milestone: "La desintegración total de Cell"},
		{SeriesID: s, SagaID: "cell", NumberStart: 193, NumberEnd: 193, Title: "Los deseos a Shenlong", Milestone: "Shenlong revive a Trunks y retira la bomba del cuerpo de la Androide 18 a petición de Krillin."},
		{SeriesID: s, SagaID: "cell", NumberStart: 194, NumberEnd: 194, Title: "La paz en el futuro de Trunks", Villains: []string{"Androide 17 del Futuro", "Androide 18 del Futuro", "Cell del Futuro"}, Milestone: "La paz en el futuro de Trunks"},
		{SeriesID: s, SagaID: "torneo-otro-mundo", NumberStart: 195, NumberEnd: 195, Title: "Rebelión en el Infierno", Villains: []string{"Pikkon"}, Milestone: "Rebelión en el Infierno"},
		{SeriesID: s, SagaID: "torneo-otro-mundo", NumberStart: 196, NumberEnd: 196, Title: "El Torneo del Otro Mundo", Filler: true, Milestone: "El Gran Kaio-sama organiza un torneo entre los 4 cuadrantes del universo."},
		{SeriesID: s, SagaID: "torneo-otro-mundo", NumberStart: 197, NumberEnd: 197, Title: "Las semifinales en el cielo", Filler: true, Milestone: "Goku vence a Arqua y avanza a la final contra Pikkon."},
		{SeriesID: s, SagaID: "torneo-otro-mundo", NumberStart: 198, NumberEnd: 198, Title: "Final: Goku vs. Pikkon", Villains: []string{"Pikkon"}, Milestone: "Final: Goku vs. Pikkon"},
		{SeriesID: s, SagaID: "torneo-otro-mundo", NumberStart: 199, NumberEnd: 199, Title: "El desenlace del torneo", Filler: true, Milestone: "El Gran Kaio-sama descalifica a ambos por tocar el techo del cuadrilátero al mismo tiempo."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 200, NumberEnd: 200, Title: "Gohan va a la preparatoria", Milestone: "Gohan (16 años) ingresa a la preparatoria Estrella Naranja en Ciudad Satán."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 201, NumberEnd: 201, Title: "El nacimiento del Gran Saiyaman", Milestone: "Bulma construye el reloj transformador para la identidad secreta del Gran Saiyaman."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 202, NumberEnd: 202, Title: "El primer rescate de Videl", Milestone: "Videl (hija de Mr. Satán) sospecha de la identidad oculta de Gohan."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 203, NumberEnd: 203, Title: "Videl en problemas", Milestone: "Gohan rescata a un bebé dinosaurio robado de un circo."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 204, NumberEnd: 204, Title: "El chantaje de Videl", Milestone: "Videl descubre que Gohan es el Gran Saiyaman y lo obliga a enseñarle a volar y participar en el torneo."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 205, NumberEnd: 205, Title: "Goku regresa por 1 día", Milestone: "Goku comunica desde el Más Allá que Uranai Baba le otorgará 24 horas para pelear en el 25° Torneo."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 206, NumberEnd: 206, Title: "Goten y Trunks sorprenden", Milestone: "Goten y Trunks revelan que ya se transforman en Super Saiyajin a su corta edad."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 207, NumberEnd: 207, Title: "El entrenamiento de vuelo de Videl", Milestone: "Gohan enseña el control de ki y la técnica del vuelo (Bukujutsu) a Videl."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 208, NumberEnd: 208, Title: "El reencuentro de los Guerreros Z", Milestone: "Goku regresa a la Tierra por 24 horas y conoce a su segundo hijo Goten."},
		{SeriesID: s, SagaID: "gran-saiyaman", NumberStart: 209, NumberEnd: 209, Title: "La prueba de fuerza Punch Machine", Milestone: "Vegeta destruye la máquina medidora de puñetazos de un solo golpe."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 210, NumberEnd: 210, Title: "Trunks gana el torneo infantil", Milestone: "Trunks vence a Goten en la final de la división infantil del 25° Torneo."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 211, NumberEnd: 211, Title: "Trunks vs. Mr. Satán", Milestone: "Mr. Satán cae fuera del ring de un ligero empujón de Trunks en la exhibición."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 212, NumberEnd: 212, Title: "Mister Mighty Mask", Milestone: "Goten y Trunks noquean al peleador Mighty Mask y se disfrazan con su traje para pelear en adultos."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 213, NumberEnd: 213, Title: "El sorteo del torneo de adultos", Milestone: "Goku y Vegeta quedan emparejados en la primera ronda."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 214, NumberEnd: 214, Title: "Piccolo se rinde ante Shin", Villains: []string{"Shin (Kaioshin)"}, Milestone: "Piccolo se rinde ante Shin"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 215, NumberEnd: 215, Title: "La paliza a Videl", Villains: []string{"Spopovich"}, Milestone: "La paliza a Videl"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 216, NumberEnd: 216, Title: "La Semilla del Ermitaño curativa", Milestone: "Goku le entrega una Semilla del Ermitaño a Videl sanando sus heridas al instante."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 217, NumberEnd: 217, Title: "El robo de energía a Gohan", Villains: []string{"Spopovich", "Yamu"}, Milestone: "El robo de energía a Gohan"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 218, NumberEnd: 218, Title: "La persecución hacia la nave de Babidi", Villains: []string{"Babidi", "Dabura"}, Milestone: "La persecución hacia la nave de Babidi"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 219, NumberEnd: 219, Title: "El escupitajo de piedra de Dabura", Villains: []string{"Dabura"}, Milestone: "El escupitajo de piedra de Dabura"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 220, NumberEnd: 220, Title: "Batalla en la nave de Babidi Parte 1", Villains: []string{"Pui Pui"}, Milestone: "Goku, Vegeta y Gohan descienden por los niveles de la nave espacial de Babidi."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 221, NumberEnd: 221, Title: "Batalla en la nave de Babidi Parte 2", Villains: []string{"Pui Pui"}, Milestone: "Goku, Vegeta y Gohan descienden por los niveles de la nave espacial de Babidi."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 222, NumberEnd: 222, Title: "Batalla en la nave de Babidi Parte 3", Villains: []string{"Pui Pui"}, Milestone: "Goku, Vegeta y Gohan descienden por los niveles de la nave espacial de Babidi."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 223, NumberEnd: 223, Title: "Batalla en la nave de Babidi Parte 4", Villains: []string{"Pui Pui"}, Milestone: "Goku, Vegeta y Gohan descienden por los niveles de la nave espacial de Babidi."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 224, NumberEnd: 224, Title: "Batalla en la nave de Babidi Parte 5", Villains: []string{"Pui Pui"}, Milestone: "Goku, Vegeta y Gohan descienden por los niveles de la nave espacial de Babidi."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 225, NumberEnd: 225, Title: "Batalla en la nave de Babidi Parte 6", Villains: []string{"Pui Pui"}, Milestone: "Goku, Vegeta y Gohan descienden por los niveles de la nave espacial de Babidi."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 226, NumberEnd: 226, Title: "Vegeta vence a Yakon", Villains: []string{"Yakon"}, Milestone: "Vegeta vence a Yakon"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 227, NumberEnd: 227, Title: "Gohan vs. Dabura", Villains: []string{"Dabura"}, Milestone: "Gohan vs. Dabura"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 228, NumberEnd: 228, Title: "La manipulación mental de Babidi", Villains: []string{"Babidi", "Majin Vegeta"}, Milestone: "La manipulación mental de Babidi"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 229, NumberEnd: 229, Title: "El despertar de Majin Vegeta", Villains: []string{"Majin Vegeta"}, Milestone: "El despertar de Majin Vegeta"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 230, NumberEnd: 230, Title: "La Batalla de los Rivales: Goku vs. Vegeta", Villains: []string{"Majin Vegeta"}, Milestone: "La Batalla de los Rivales: Goku vs. Vegeta"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 231, NumberEnd: 231, Title: "La energía llena el huevo de Buu", Villains: []string{"Babidi", "Majin Buu Gordo"}, Milestone: "La energía llena el huevo de Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 232, NumberEnd: 232, Title: "El nacimiento de Majin Buu", Villains: []string{"Majin Buu Gordo"}, Milestone: "El nacimiento de Majin Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 233, NumberEnd: 233, Title: "Majin Buu convierte a Dabura en galleta", Villains: []string{"Majin Buu Gordo"}, Milestone: "Majin Buu convierte a Dabura en galleta"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 234, NumberEnd: 234, Title: "La llegada de Vegeta al huevo", Villains: []string{"Majin Buu Gordo"}, Milestone: "La llegada de Vegeta al huevo"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 235, NumberEnd: 235, Title: "La paliza a Majin Buu", Villains: []string{"Majin Buu Gordo"}, Milestone: "La paliza a Majin Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 236, NumberEnd: 236, Title: "El abrazo final a Trunks", Milestone: "Vegeta abraza a Trunks por primera vez antes de dejarlo nocaut junto a Goten."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 237, NumberEnd: 237, Title: "La Explosión Final de Majin Vegeta", Villains: []string{"Majin Buu Gordo"}, Milestone: "La Explosión Final de Majin Vegeta"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 238, NumberEnd: 238, Title: "La regeneración de Majin Buu", Villains: []string{"Majin Buu Gordo"}, Milestone: "La regeneración de Majin Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 239, NumberEnd: 239, Title: "El plan de la Danza de la Fusión", Milestone: "Goku despierta y propone enseñar la Danza de la Fusión a Goten y Trunks en el Templo."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 240, NumberEnd: 240, Title: "El planeta sagrado de los Kaioshin", Milestone: "Gohan es llevado al Planeta Sagrado para extraer la Legendaria Espada Z."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 241, NumberEnd: 241, Title: "Gohan saca la Espada Z", Milestone: "Gohan SSJ saca la pesada Espada Z del pedestal de piedra."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 242, NumberEnd: 242, Title: "Majin Buu destruye ciudades", Villains: []string{"Majin Buu Gordo", "Babidi"}, Milestone: "Majin Buu destruye ciudades"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 243, NumberEnd: 243, Title: "Goku interrumpe el paso de Babidi", Villains: []string{"Majin Buu Gordo"}, Milestone: "Goku interrumpe el paso de Babidi"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 244, NumberEnd: 244, Title: "El despertar del Super Saiyajin 3", Villains: []string{"Majin Buu Gordo"}, Milestone: "El despertar del Super Saiyajin 3"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 245, NumberEnd: 245, Title: "Goku SSJ3 vs. Majin Buu", Villains: []string{"Majin Buu Gordo"}, Milestone: "Goku SSJ3 vs. Majin Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 246, NumberEnd: 246, Title: "El nacimiento de Evil Buu", Villains: []string{"Evil Buu"}, Milestone: "El nacimiento de Evil Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 247, NumberEnd: 247, Title: "El nacimiento de Super Buu", Villains: []string{"Super Buu"}, Milestone: "El nacimiento de Super Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 248, NumberEnd: 248, Title: "Super Buu llega al Templo Sagrado", Villains: []string{"Super Buu"}, Milestone: "Super Buu llega al Templo Sagrado"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 249, NumberEnd: 249, Title: "El exterminio de la raza humana", Villains: []string{"Super Buu"}, Milestone: "El exterminio de la raza humana"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 250, NumberEnd: 250, Title: "La entrada a la Habitación del Tiempo", Villains: []string{"Super Buu"}, Milestone: "La entrada a la Habitación del Tiempo"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 251, NumberEnd: 251, Title: "El debut de Gotenks", Villains: []string{"Super Buu"}, Milestone: "El debut de Gotenks"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 252, NumberEnd: 252, Title: "Los Ataques Kamikaze de los Fantasmas", Villains: []string{"Super Buu"}, Milestone: "Los Ataques Kamikaze de los Fantasmas"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 253, NumberEnd: 253, Title: "La destrucción de la puerta dimensional", Villains: []string{"Super Buu"}, Milestone: "La destrucción de la puerta dimensional"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 254, NumberEnd: 254, Title: "Super Buu escapa de la dimensión", Villains: []string{"Super Buu"}, Milestone: "Super Buu escapa de la dimensión"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 255, NumberEnd: 255, Title: "Gotenks Super Saiyajin 3", Villains: []string{"Super Buu"}, Milestone: "Gotenks Super Saiyajin 3"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 256, NumberEnd: 256, Title: "La expiración del tiempo de la fusión", Villains: []string{"Super Buu"}, Milestone: "La expiración del tiempo de la fusión"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 257, NumberEnd: 257, Title: "La llegada de Gohan Definitivo", Villains: []string{"Super Buu"}, Milestone: "La llegada de Gohan Definitivo"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 258, NumberEnd: 258, Title: "Gohan Definitivo masacra a Super Buu", Villains: []string{"Super Buu"}, Milestone: "Gohan Definitivo masacra a Super Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 259, NumberEnd: 259, Title: "La trampa de absorción de Super Buu", Villains: []string{"Super Buu"}, Milestone: "La trampa de absorción de Super Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 260, NumberEnd: 260, Title: "El nacimiento de Buutenks", Villains: []string{"Buutenks"}, Milestone: "El nacimiento de Buutenks"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 261, NumberEnd: 261, Title: "Buutenks supera a Gohan", Villains: []string{"Buutenks"}, Milestone: "Buutenks supera a Gohan"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 262, NumberEnd: 262, Title: "El sacrificio del Anciano Kaioshin", Milestone: "El Anciano Kaioshin le regala su vida a Goku para que regrese a la Tierra con los Pendientes Pothala."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 263, NumberEnd: 263, Title: "La expiración de la fusión dentro de Buu", Villains: []string{"Super Buu"}, Milestone: "La expiración de la fusión dentro de Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 264, NumberEnd: 264, Title: "El nacimiento de Buuhan", Villains: []string{"Buuhan"}, Milestone: "El nacimiento de Buuhan"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 265, NumberEnd: 265, Title: "Goku y Vegeta en el campo de batalla", Villains: []string{"Buuhan"}, Milestone: "Goku y Vegeta en el campo de batalla"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 266, NumberEnd: 266, Title: "La unión de los Pendientes Pothala", Villains: []string{"Buuhan"}, Milestone: "La unión de los Pendientes Pothala"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 267, NumberEnd: 267, Title: "El nacimiento del guerrero Vegetto", Villains: []string{"Buuhan"}, Milestone: "El nacimiento del guerrero Vegetto"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 268, NumberEnd: 268, Title: "El guerrero definitivo: Vegetto", Villains: []string{"Buuhan"}, Milestone: "El guerrero definitivo: Vegetto"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 269, NumberEnd: 269, Title: "Vegetto transformado en caramelo de café", Villains: []string{"Buuhan"}, Milestone: "Vegetto transformado en caramelo de café"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 270, NumberEnd: 270, Title: "El ingreso al cuerpo de Buuhan", Villains: []string{"Buuhan"}, Milestone: "El ingreso al cuerpo de Buuhan"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 271, NumberEnd: 271, Title: "La separación de la fusión Pothala", Villains: []string{"Super Buu"}, Milestone: "La separación de la fusión Pothala"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 272, NumberEnd: 272, Title: "El rescate de Gohan, Trunks, Goten y Piccolo", Villains: []string{"Super Buu"}, Milestone: "El rescate de Gohan, Trunks, Goten y Piccolo"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 273, NumberEnd: 273, Title: "La desconexión del Majin Buu Gordo", Villains: []string{"Super Buu"}, Milestone: "La desconexión del Majin Buu Gordo"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 274, NumberEnd: 274, Title: "La huida del cuerpo de Buu", Villains: []string{"Super Buu"}, Milestone: "La huida del cuerpo de Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 275, NumberEnd: 275, Title: "El nacimiento de Kid Buu", Villains: []string{"Kid Buu"}, Milestone: "El nacimiento de Kid Buu"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 276, NumberEnd: 276, Title: "La destrucción de la Tierra", Villains: []string{"Kid Buu"}, Milestone: "La destrucción de la Tierra"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 277, NumberEnd: 277, Title: "El rescate de Kaio-sama", Villains: []string{"Kid Buu"}, Milestone: "El rescate de Kaio-sama"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 278, NumberEnd: 278, Title: "Kid Buu persigue por los planetas", Villains: []string{"Kid Buu"}, Milestone: "Kid Buu persigue por los planetas"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 279, NumberEnd: 279, Title: "La batalla decisiva en el Planeta Sagrado", Villains: []string{"Kid Buu"}, Milestone: "La batalla decisiva en el Planeta Sagrado"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 280, NumberEnd: 280, Title: "El desgaste del Super Saiyajin 3", Villains: []string{"Kid Buu"}, Milestone: "El desgaste del Super Saiyajin 3"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 281, NumberEnd: 281, Title: "Vegeta resiste el tiempo de Goku", Villains: []string{"Kid Buu"}, Milestone: "Vegeta resiste el tiempo de Goku"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 282, NumberEnd: 282, Title: "La intervención del Majin Buu Gordo", Villains: []string{"Kid Buu", "Majin Buu Gordo"}, Milestone: "La intervención del Majin Buu Gordo"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 283, NumberEnd: 283, Title: "El plan de la Super Genkidama", Villains: []string{"Kid Buu"}, Milestone: "El plan de la Super Genkidama"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 284, NumberEnd: 284, Title: "La voz de Mr. Satán convence al mundo", Villains: []string{"Kid Buu"}, Milestone: "La voz de Mr. Satán convence al mundo"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 285, NumberEnd: 285, Title: "La Super Genkidama Universal", Villains: []string{"Kid Buu"}, Milestone: "La Super Genkidama Universal"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 286, NumberEnd: 286, Title: "¡Gracias, Goku!", Villains: []string{"Kid Buu"}, Milestone: "¡Gracias, Goku!"},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 287, NumberEnd: 287, Title: "La paz regresa y el perdón a Buu", Milestone: "Shenlong borra los recuerdos de los humanos sobre Majin Buu permitiendo que el Buu Gordo viva en paz con Mr. Satán."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 288, NumberEnd: 288, Title: "La fiesta en la casa de Bulma", Filler: true, Milestone: "Reunión pacífica de los Guerreros Z en los jardines de la Corporación Cápula."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 289, NumberEnd: 289, Title: "10 años después: El 28° Torneo", Milestone: "Salto temporal de 10 años; presentación de Pan (4 años) y la nueva generación."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 290, NumberEnd: 290, Title: "La reencarnación de Buu: Uub", Milestone: "Goku enfrenta al niño Uub (10 años), reencarnación de Kid Buu, en la primera ronda del torneo."},
		{SeriesID: s, SagaID: "majin-buu", NumberStart: 291, NumberEnd: 291, Title: "La partida de Goku con Uub", Milestone: "Goku toma a Uub sobre sus espaldas y parte volando a entrenarlo a su aldea natal como el nuevo protector de la Tierra."},

	}
}
